." Manpage for qa_test_logrotate.
." Contact David Mulder <dmulder@suse.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_logrotate man page"
.SH NAME
qa_test_logrotate
.SH SYNOPSIS
/usr/share/qa/qa_sample/test_logrotate_test-run
.SH TYPE
test
.SH DESCRIPTION
Tests the following features of logrotate: addextension, compression, copy_log, dateformat, force_rotate, ifempty, log_order, log_size, no_force_rotate, notifempty, and remove_old_logs.
.br
Tests are written in Python.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, our code.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
David Mulder <dmulder@suse.com>
.SH MAINTAINER
David Mulder <dmulder@suse.com>
