." Manpage for qa_test_coreutils.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_coreutils man page"
.SH NAME
qa_test_coreutils
.SH SYNOPSIS
/usr/share/qa/tools/test_coreutils-run
.SH TYPE
Function Test
.SH DESCRIPTION
qa_test_coreutils is a test tool for testing coreutils (Linux common commands, say ls, cd etc.)
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None
.SH WARNINGS
Don't press Ctrl-C while testing run.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
The code developed for this package is internally developed. However, there is a directory called orig_test_suite which contains the original, unmodified GPL test suite. So, that code is only included because we run those tests, but the scripts above that directory are internally created.
.SH LICENSE
SUSE Proprietary (although the original, standalone testsuite is GPL v2 or later). Still waiting to see if that means the entire package needs to be GPL v2 or later also.
.SH UPSTREAM
None.
.SH AUTHOR
kmachalkova <kmachalkova@novell.com>
.SH MAINTAINER
Leon Wang <llwang@novell.com>
