." Manpage for qa_test_iosched.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_iosched man page"
.SH NAME
qa_test_iosched
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Internal I/O benchmark test, which uses the open-source tiobench benchmark. It tries small benchmarks on all available ioschedulers for the device.
.SH README
qa_test_iosched runs the open-source IO benchmark tiobench on all available ioschedulers for the device. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
None.
.SH UPSTREAM
http://qa.suse.de/
.SH AUTHOR
Frank Seidel <fseidel@suse.de>
.SH MAINTAINER
ldai@novell.com
