." Manpage for qa_test_gnutls.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_gnutls man page"
.SH NAME
qa_test_gnutls
.SH SYNOPSIS
None.
.SH TYPE
None.
.SH DESCRIPTION
Test cases for the gnutls package.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
None.
.SH MAINTAINER
kwg@novell.com
