." Manpage for qa_test_dbench.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_dbench man page"
.SH NAME
qa_test_dbench
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Dbench is a file system benchmark that generates load patterns similar to those of the commercial Netbench benchmark, but without requiring a lab of Windows load generators to run. It is now considered a de facto standard for generating load on the Linux VFS.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, 2 patches.
.SH LICENSE
License: GPL v2 or later. Spec file license: GPL v2 or later.
.SH UPSTREAM
http://samba.org/ftp/tridge/qa_test_dbench/
.SH AUTHOR
Andrew Tridgell <tridge@samba.org>
.SH MAINTAINER
Vilem Marsik <VMarsik@novell.com>
