#!/bin/sh
#sut_timeout 3600

ctcsdir="/usr/lib/ctcs2"
basedir="/usr/share/qa/qa_test_dbench"

service cron stop

$ctcsdir/tools/run $basedir/tcf/dbench-default.tcf
sleep 120
$ctcsdir/tools/run $basedir/tcf/dbench-syncIO.tcf

