." Manpage for qa_test_cracklib.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_cracklib man page"
.SH NAME
qa_test_cracklib
.SH SYNOPSIS
/usr/share/qa/tools/test_cracklib-run
.SH TYPE
function test
.SH DESCRIPTION
CrackLib tests passwords to determine whether they match certain security-oriented characteristics, with the purpose of stopping users from choosing passwords that are easy to guess.
.br
This suite tests cracklib.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
A temp user will be created, and the suite will try to assign passwords to this user.
.SH COMMON PROBLEMS
No serious problems.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internally developed.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Katarina Machalkova <KMachalkova@novell.com>, Lukas, Michael Schroeder, Rudiger
.SH MAINTAINER
Arthur Guo <aguo@novell.com>
