." Manpage for qa_test_netio.
." Contact Yi Xu <yxu@suse.com> to correct errors or typos.
.TH man 8 "10 Dec 2012" "1.0" "qa_test_netio man page"
.SH NAME
qa_test_netio
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
It is a network benchmark for OS/2 2.x, Windows, Linux and Unix. It measures the net throughput of a network via TCP and UDP protocols using various different packet sizes.
.br
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
One instance has to run on one machine as a server process, another instance is used on another machine to perform the benchmark. When executed without arguments, the program will explain its usage.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://www.ars.de/ars/ars.nsf/docs/netio
.SH AUTHOR
Kai Uwe Rommel
.SH MAINTAINER
Yi Xu <yxu@suse.com>
