#!/bin/sh
#sut_timeout 3600

ctcsdir="/usr/lib/ctcs2"
basedir="/usr/share/qa/qa_test_dbench-4_0"

ostag=`cat /etc/issue|perl -ne 'if(/(\w+)\s+(\d+\.?\d+)\s+("?\w+)/i){$b=$2;$c=$3;$c=~s/[[:alpha:]]|\"//g;$a=$b.".".$c;$a=~s/\.$//;print $a;}'`
newtag=12
flag=`expr $ostag \> $newtag`
if [ $flag -ne 1 ]
then
/etc/init.d/cron stop
else
systemctl stop cron
fi

$ctcsdir/tools/run $basedir/tcf/dbench-o_sync-4_0.tcf

