#!/bin/sh

ctcsdir="/usr/lib/ctcs2"
TCF_DIR="/usr/share/qa/tcf"

if [ -x /etc/init.d/cron ];then
    /etc/init.d/cron stop
else
    systemctl stop cron
fi

ABUILD_FS=$(grep '/abuild' /proc/mounts  | awk '{print $3}')
case ${ABUILD_FS} in
    "")
        mkdir -p /abuild
        ABUILD_FS="root"
        ;;
    *)
        echo "[dbench-4_0_osync] The filesystem on /abuild is ${ABUILD_FS}"
        ;;
esac

TCF_FILE="${TCF_DIR}/dbench4_osync_${ABUILD_FS}.tcf"
echo > ${TCF_FILE}
for NUM in 1 48 128 192 256 500;do
cat <<EOF >> ${TCF_FILE}
timer 8h
fg 1 dbench4-osync /usr/share/qa/qa_test_dbench-4_0/do_dbench -o -s -n ${NUM}
wait
EOF
done

$ctcsdir/tools/run ${TCF_FILE}

