." Manpage for qa_test_newburn.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_newburn man page"
.SH NAME
qa_test_newburn
.SH SYNOPSIS
/usr/lib/ctcs2/tools/test_qa_test_newburn-run
.SH TYPE
Stress test for disk/memory.
.SH DESCRIPTION
This suite can be divided into two parts: qa_test_newburn and qa_test_newburn-memtst.
.br
"qa_test_newburn" focuses on disk stress tests, while "qa_test_newburn-memtst" focuses on memory testing.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
After collecting hwinfo, test process will keep running repetitively for 24 hours,
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
All fixed.
.SH DISTRIBUTION
External (partially), Lots of our own code.
.SH LICENSE
License: GPL v2 or later. Spec file license: LPGL v2.1 or later. This test was originally part of the CTCS package, however, we have separated it out and it will probably need to be released separately.
.SH UPSTREAM
None.
.SH AUTHOR
Various people from VA Linux <john.doe@novell.com>
.SH MAINTAINER
Arthur Guo <aguo@novell.com>
