." Manpage for qa_test_yast_HA.
." Contact Calen Chen <cachen@suse.com> to correct errors or typos.
.TH man 8 "28 Feb 2012" "1.0" "qa_test_yast_HA man page"
.SH NAME
qa_test_yast_HA
.SH SYNOPSIS
/usr/share/qa/qa_test_yast_HA/test_yast_HA-run or /usr/share/qa/qa_test_yast_HA/qa_test_yast_cluster/yast_cluster*.py
.SH TYPE
UI function test
.SH DESCRIPTION
Internal test suite for testing the HA collaboration Yast UI tools.
.br
Scripts are written in Python.
.SH README
qa_test_yast_HA tests the following: Yast cluster, Yast iplb, Yast drbd.
.SH OPTIONS
None.
.SH WHAT IT DOES
/usr/share/qa/qa_test_yast_HA/qa_test_*/*.py will be run.
.br
A series of UI tests of HA Yast UI tools will be implemented automatically.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal only.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Calen Chen <cachen@novell.com>
.SH MAINTAINER
Calen Chen <cachen@novell.com>
