#!/usr/bin/python3
#
# Here is a mapping of the run item in qaset to the case in reportdb.
# It is better to have a real database like metadata.
# So it is better to be shared by the server and client
#

class Error(Exception):
    pass
class InvalidSuiteError(Error):
    def __str__(self):
        return "No suite {}".format(self.args[0])

cases = {
    "lmbench-local":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench-local"]
    },
    "lmbench-syscall":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench-syscall"]
    },
    "lmbench-ops":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench-ops"]
    },
    "lmbench-file":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench-file"]
    },
    "lmbench-ctx":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench-ctx"]
    },
    "lmbench-bcopy":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench-bcopy"]
    },
    "lmbench-mem":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench-mem"]
    },
    "kernbench":{
        "category":"misc",
        "category_value":"",
        "cases":["kernbench"]
    },
    "reaim_alltest":{
        "category":"misc",
        "category_value":"",
        "cases":["reaim-alltest"]
    },
    "qa_siege_performance":{
        "category":"misc",
        "category_value":"",
        "cases":["qa_siege_performance"]
    },
    "sysbench-sys":{
        "category":"syslib",
        "category_value":"",
        "cases":["sysbench-cpu", "sysbench-fileio",
                 "sysbench-memory", "sysbench-mutex", "sysbench-threads"]
    },
    "libmicro_bench":{
        "category":"syslib",
        "category_value":"",
        "cases":["libmicro-bench"]
    },
    "libmicro-contextswitch":{
        "category":"syslib",
        "category_value":"",
        "cases":["libmicro-contextswitch"]
    },
    "libmicro-file":{
        "category":"syslib",
        "category_value":"",
        "cases":["libmicro-file"]
    },
    "libmicro-memory":{
        "category":"syslib",
        "category_value":"",
        "cases":["libmicro-memory"]
    },
    "libmicro-regular":{
        "category":"syslib",
        "category_value":"",
        "cases":["libmicro-regular"]
    },
    "libmicro-process":{
        "category":"syslib",
        "category_value":"",
        "cases":["libmicro-process"]
    },
    "libmicro-socket":{
        "category":"syslib",
        "category_value":"",
        "cases":["libmicro-socket"]
    },
    "lmbench":{
        "category":"syslib",
        "category_value":"",
        "cases":["lmbench"]
    },
    "netperf-peer-loop":{
        "category":"network",
        "category_value":"",
        "cases":["netperf-loop-tcp", "netperf-loop-udp"]
    },
    "netperf-peer-loop6":{
        "category":"network",
        "category_value":"",
        "cases":["netperf-loop-tcp", "netperf-loop-udp"]
    },
    "netperf-peer-loop6-udp":{
        "category":"network",
        "category_value":"",
        "cases":["netperf-loop-udp"]
    },
    "netperf-peer-loop-udp":{
        "category":"network",
        "category_value":"",
        "cases":["netperf-loop-udp"]
    },
    "netperf-peer-loop-tcp":{
        "category":"network",
        "category_value":"",
        "cases":["netperf-loop-tcp"]
    },
    "netperf-peer-loop6-tcp":{
        "category":"network",
        "category_value":"",
        "cases":["netperf-loop-tcp"]
    },
    "reaim_disk_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["reaim-ioperf"]
    },
    "reaim_disk_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["reaim-ioperf"]
    },
    "reaim_disk_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["reaim-ioperf"]
    },
    "reaim_disk_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["reaim-ioperf"]
    },
    "qa_iozone_doublemem_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["iozone-doublemem-async", "iozone-doublemem-fsync"]
    },
    "qa_iozone_doublemem_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["iozone-doublemem-async", "iozone-doublemem-fsync"]
    },
    "qa_iozone_doublemem_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["iozone-doublemem-async", "iozone-doublemem-fsync"]
    },
    "qa_iozone_doublemem_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["iozone-doublemem-async", "iozone-doublemem-fsync"]
    },
    "qa_tiobench_async_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["tiobench-doublemem-async"]
    },
    "qa_tiobench_async_xfs":{
        "category":"io",
        "category_value":"xfs",
        "suite":"qa_tiobench_async_xfs",
        "cases":["tiobench-doublemem-async"]
    },
    "qa_tiobench_async_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "suite":"qa_tiobench_async_btrfs",
        "cases":["tiobench-doublemem-async"]
    },
    "qa_tiobench_async_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["tiobench-doublemem-async"]
    },
    "bonnie++_async_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["bonnie++-async"]
    },
    "bonnie++_async_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["bonnie++-async"]
    },
    "bonnie++_async_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["bonnie++-async"]
    },
    "bonnie++_async_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["bonnie++-async"]
    },
    "bonnie++_fsync_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["bonnie++-fsync"]
    },
    "bonnie++_fsync_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["bonnie++-fsync"]
    },
    "bonnie++_fsync_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["bonnie++-fsync"]
    },
    "bonnie++_fsync_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["bonnie++-fsync"]
    },
    "sysbench_oltp_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["sysbench-oltp"]
    },
    "sysbench_oltp_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["sysbench-oltp"]
    },
    "sysbench_oltp_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["sysbench-oltp"]
    },
    "sysbench_oltp_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["sysbench-oltp"]
    },
    "dbench4_async_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["dbench4-async"]
    },
    "dbench4_async_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["dbench4-async"]
    },
    "dbench4_async_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["dbench4-async"]
    },
    "dbench4_async_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["dbench4-async"]
    },
    "pgbench_small_rw_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["pgbench-small-rw"]
    },
    "pgbench_small_rw_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["pgbench-small-rw"]
    },
    "pgbench_small_rw_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["pgbench-small-rw"]
    },
    "pgbench_small_rw_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["pgbench-small-rw"]
    },
    "pgbench_small_ro_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["pgbench-small-ro"]
    },
    "pgbench_small_ro_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["pgbench-small-ro"]
    },
    "pgbench_small_ro_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["pgbench-small-ro"]
    },
    "pgbench_small_ro_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["pgbench-small-ro"]
    },
    "dbench4_fsync_ext3":{
        "category":"io",
        "category_value":"ext3",
        "cases":["dbench4-fsync"]
    },
    "dbench4_fsync_xfs":{
        "category":"io",
        "category_value":"xfs",
        "cases":["dbench4-fsync"]
    },
    "dbench4_fsync_btrfs":{
        "category":"io",
        "category_value":"btrfs",
        "cases":["dbench4-fsync"]
    },
    "dbench4_fsync_ext4":{
        "category":"io",
        "category_value":"ext4",
        "cases":["dbench4-fsync"]
    },
}

qaset_run2ctcs2_suite = {
    "kernbench":"kernbench",
    "reaim_allworks":"reaim-alltest",
    "siege":"qa_siege_performance",
    "sysbench_sys":"sysbench-sys",
    "libmicro_bench":"libmicro-bench",
    "lmbench_bench":"lmbench",
    "netperf_loop4":"netperf-peer-loop",
    "netperf_loop6":"netperf-peer-loop6",
    "reaim_ioperf_ext3":"reaim_disk_ext3",
    "reaim_ioperf_xfs":"reaim_disk_xfs",
    "reaim_ioperf_btrfs":"reaim_disk_btrfs",
    "reaim_ioperf_ext4":"reaim_disk_ext4",
    "iozone_doublemem_ext3":"qa_iozone_doublemem_ext3",
    "iozone_doublemem_xfs":"qa_iozone_doublemem_xfs",
    "iozone_doublemem_btrfs":"qa_iozone_doublemem_btrfs",
    "iozone_doublemem_ext4":"qa_iozone_doublemem_ext4",
    "tiobench_doublemem_async_ext3":"qa_tiobench_async_ext3",
    "tiobench_doublemem_async_xfs":"qa_tiobench_async_xfs",
    "tiobench_doublemem_async_btrfs":"qa_tiobench_async_btrfs",
    "tiobench_doublemem_async_ext4":"qa_tiobench_async_ext4",
    "bonniepp_async_ext3":"bonnie++_async_ext3",
    "bonniepp_async_xfs":"bonnie++_async_xfs",
    "bonniepp_async_btrfs":"bonnie++_async_btrfs",
    "bonniepp_async_ext4":"bonnie++_async_ext4",
    "bonniepp_fsync_ext3":"bonnie++_fsync_ext3",
    "bonniepp_fsync_xfs":"bonnie++_fsync_xfs",
    "bonniepp_fsync_btrfs":"bonnie++_fsync_btrfs",
    "bonniepp_fsync_ext4":"bonnie++_fsync_ext4",
    "sysbench_oltp_ext3":"sysbench_oltp_ext3",
    "sysbench_oltp_xfs":"sysbench_oltp_xfs",
    "sysbench_oltp_btrfs":"sysbench_oltp_btrfs",
    "sysbench_oltp_ext4":"sysbench_oltp_ext4",
    "dbench4_async_ext3":"dbench4_async_ext3",
    "dbench4_async_xfs":"dbench4_async_xfs",
    "dbench4_async_btrfs":"dbench4_async_btrfs",
    "dbench4_async_ext4":"dbench4_async_ext4",
    "pgbench_small_rw_ext3":"pgbench_small_rw_ext3",
    "pgbench_small_rw_xfs":"pgbench_small_rw_xfs",
    "pgbench_small_rw_btrfs":"pgbench_small_rw_btrfs",
    "pgbench_small_rw_ext4":"pgbench_small_rw_ext4",
    "pgbench_small_ro_ext3":"pgbench_small_ro_ext3",
    "pgbench_small_ro_xfs":"pgbench_small_ro_xfs",
    "pgbench_small_ro_btrfs":"pgbench_small_ro_btrfs",
    "pgbench_small_ro_ext4":"pgbench_small_ro_ext4",
    "dbench4_fsync_ext3":"dbench4_fsync_ext3",
    "dbench4_fsync_xfs":"dbench4_fsync_xfs",
    "dbench4_fsync_btrfs":"dbench4_fsync_btrfs",
    "dbench4_fsync_ext4":"dbench4_fsync_ext4"
}

def get_cases_by_suite(suite):
    try:
        record = cases[suite]
        return record
    except KeyError as e:
        raise InvalidSuiteError("ctcs2 {}".format(suite))

def qaset_case2report_case(qaset_case):
    try:
        suite = qaset_run2ctcs2_suite[qaset_case]
    except KeyError as e:
        raise InvalidSuiteError("qaset {}".format(qaset_case))
    record = get_cases_by_suite(suite)
    record = cases[suite]
    record = record.copy()
    record["suite"] = suite
    return record
