." Manpage for qa_test_specweb.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_specweb man page"
.SH NAME
qa_test_specweb
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Specweb benchmark. Tests local web server from one local client with various number of simultaneous connections.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Proprietary.
.SH LICENSE
Proprietary SPEC. Seems to be owned by SPEC; requires license and payment; likely cannot distribute.
.SH UPSTREAM
None.
.SH AUTHOR
None.
.SH MAINTAINER
tbd
