." Manpage for qa_test_reaim.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_reaim man page"
.SH NAME
qa_test_reaim
.SH SYNOPSIS
/usr/lib/ctcs2/tools/test_qa_test_reaim-run
.SH TYPE
Performance test
.SH DESCRIPTION
This suite is a part of ltp, testing memory.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
Don't press Ctrl-C while testing run.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, 10 patches.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://sourceforge.net/projects/re-aim-7
.SH AUTHOR
Gernot Payer <gpayer@suse.de>, VA Linux
.SH MAINTAINER
Leon Wang <llwang@novell.com>
