." Manpage for qa_test_php5.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_php5 man page"
.SH NAME
qa_test_php5
.SH SYNOPSIS
/usr/share/qa/tools/test_php5-run
.SH TYPE
Function test suite for php5
.SH DESCRIPTION
This package contains a wide range of php5 tests, including basic language constructs (operators, control flow, etc), object oriented language constructs (classes, etc), basic functions tests (strlen, "function" construct, etc), and PHP extensions (json, mbstring, etc).
.SH README
None.
.SH OPTIONS
None
.SH WHAT IT DOES
These tests include basic language constructs (operators, control flow, etc)
.br
The tcf file is generated while installing suite.
.SH COMMON PROBLEMS
Require read STDIN, see bugs below.
.SH WARNINGS
Implement this test suite through hamsta.
.br
Use the new version of ctcs2.
.SH SEE ALSO
None.
.SH BUGS
#216220.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
PHP
.SH UPSTREAM
None.
.SH AUTHOR
Various people from php.net <php.net>
.SH MAINTAINER
Nathan Zhao <jtzhao@suse.com>
