# ****************************************************************************
# Copyright (c) 2013 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#

fg 1 @@name@@ /usr/share/qa/qa_test_iozone/abuildinfo
#benchparser /usr/share/qa/qa_test_iozone/iozoneparser_4-32G

fg 1 @@name@@ /usr/bin/iozone -a -n @@IOZONE_MIN_SIZE@@ -g @@IOZONE_MAX_SIZE@@ -y  @@IOZONE_MIN_BLK_SIZE@@ -q @@IOZONE_MAX_BLK_SIZE@@ -i 0 -i 1 -i 2 -i 3 -f /abuild/iozone -R

fg 1 @@name@@-fsync /usr/bin/iozone -e -a -n @@IOZONE_MIN_SIZE@@ -g @@IOZONE_MAX_SIZE@@ -y  @@IOZONE_MIN_BLK_SIZE@@ -q @@IOZONE_MAX_BLK_SIZE@@ -i 0 -i 1 -i 2 -i 3 -f /abuild/iozone -R

wait

