." Manpage for qa_test_cabextract.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_cabextract man page"
.SH NAME
qa_test_cabextract
.SH SYNOPSIS
/usr/share/qa/tools/test_cabextract-run
.SH TYPE
function test
.SH DESCRIPTION
This is a test suite testing different compressed files.
.br
The test suite use the ctcs2 framework and is written in BASH.
.SH README
None.
.SH OPTIONS
None
.SH WHAT IT DOES
The test suite runs compression tests.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal development.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Lukas Lipavsky <llipavsky@suse.cz>
.SH MAINTAINER
Andrej Semen <asemen@novell.com>
