." Manpage for qa_test_aim9.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_aim9 man page"
.SH NAME
qa_test_aim9
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
The AIM Independent Resource Benchmark exercises and times each component of a UNIX computer system, independently. The benchmark uses 58 subtests to generate absolute processing rates, in operations per second, for subsystems, I/O transfers, function calls, and UNIX system calls.
.br
Test results can be used to compare different machines on a
test-by-test basis or to measure the success or failure of system
tuning and configuration changes on a single system. This benchmark
yields specific results on a per-test basis.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://aimbench.sourceforge.net/
.SH AUTHOR
None.
.SH MAINTAINER
Vilem Marsik <VMarsik@novell.com>
