#!/bin/bash

# env $BUILDARGS can be used to provide additional atguments to osc build
# example BUILDARGS="--clean"

this="`which "$0"`"
cd "`dirname "$this"`"
source shared.sh

assert_command osc

[ $# -ne 1 ] && echo "Usage: $0 <package>" && exit
[ ! -d "$1" ] && echo "Error: $1 is not a directory." && exit 1

package="`basename "$1"`"
[ -z "$REPOSITORY" ] && REPOSITORY="SUSE_SLE-11-SP2_GA"
[ -z "$ARCH" ] && ARCH=`arch`

# initialize dir as BS package (but keep current BS metadata)
dir=`mktemp -d`
pushd $dir > /dev/null

if ! osc_init "$project" "$package" ; then
	echo "Error: Package $package does not exist in the project $project." >&2
	rm -fr $dir
	exit 1
fi
popd > /dev/null

# prepare and copy files to the ibs projects
cd "$1"
package_prepare
copy_package_sources "$dir"
package_cleanup
cd - > /dev/null

# build
cd $dir
$iosc help repairwc > /dev/null 2>&1 &&  $iosc repairwc .
echo
echo '+-- RUNNING BUILD ----------------------------------------------------------------'
echo
$iosc build $BUILDARGS -k "$DESTDIR" --no-verify $REPOSITORY $ARCH
res=$?
echo
echo '+-- BUILD FINISHED ---------------------------------------------------------------'
echo
rm -fr "$dir"

# create directory structure
cd "$DESTDIR"
for p in *.rpm ; do
	[ "$p" == '*.rpm' ] && continue
	arch="`echo $p | sed 's/^.*\.\([^\.]\+\)\.rpm/\1/'`"
	mkdir -p $arch
	mv $p $arch
done

exit $res
