#! /bin/bash

# Install the test suites packages

/usr/share/qa/qa_testset_kernel/install.sh

echo -e "You can run acceptance/kernel/regression tests now.\n"

#start all tests

echo -e "\nBEWARE: ALL TESTS are running, Please see screen -r tests\n" > /etc/motd

echo -e "All tests starts now, see screen -r tests for details\n"

echo -e "========== Starting Testing ==========\n"


screen -L -S tests -m /bin/bash -c '(
	/usr/share/qa/qa_testset_kernel/run.sh
	)'


