." Manpage for qa_test_multipath.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_multipath man page"
.SH NAME
qa_test_multipath
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Test cases for multipath software and hardware tests.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
License: n/a. Spec file license: GPL v2 or later.
.SH UPSTREAM
http://fake.suse.de
.SH AUTHOR
Dinar Valeev <dvaleev@novell.com>
.SH MAINTAINER
dvaleev@novell.com
