." Manpage for qa_test_tar.
.TH man 8 "7 Jan 2014" "1.0" "qa_test_tar man page"
.SH NAME
qa_test_tar
.SH SYNOPSIS
/usr/share/qa/tools/test_tar-run
.SH TYPE
QA integration package for tar-tests rpm.
.SH DESCRIPTION
Runs tar upstream testsuite.
.SH README
None.
.SH OPTIONS
None.
.SH WARNINGS
None.
.SH SEE ALSO
tar upstream project.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal development. Internal license.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Lukas Lipavsky <llipavsky@suse.com>
.SH MAINTAINER
Lukas Lipavsky <llipavsky@suse.com>
