." Manpage for qa_test_lvm2.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_lvm2 man page"
.SH NAME
qa_test_lvm2
.SH SYNOPSIS
None.
.SH TYPE
None.
.SH DESCRIPTION
Regression tests for Logical Volume Manager.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
None.
.SH UPSTREAM
None.
.SH AUTHOR
Dinar Valeev <dvaleev@novell.com>
.SH MAINTAINER
None.
