." Manpage for qa_test_cts.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_cts man page"
.SH NAME
qa_test_cts
.SH SYNOPSIS
None.
.SH TYPE
None.
.SH DESCRIPTION
This is an HA test package that can be used to 
test base function of HA.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Jerry Tang <jtang@novell.com>
.SH MAINTAINER
None.
