." Manpage for qa_test_pgbench.
." Contact Lance Wang <LZWang@suse.com> to correct errors or typos.
.TH man 8 "30 Aug 2014" "1.0" "qa_test_pgbench man page"
.SH NAME
qa_test_pgbench
.SH SYNOPSIS
/usr/share/qa/tools/test_pgbench-run
.SH TYPE
function test
.SH DESCRIPTION
a test script using pgbench to test the IO performance.
.SH README
None.
.SH OPTIONS
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
Make sure "postgresql93 postgresql93-contrib postgresql-init postgresql93-server" patterns have already be installed in SUT.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH LICENSE
GPL v2
.SH UPSTREAM
None.
.SH AUTHOR
Lance Wang <LZWang@suse.com>
.SH MAINTAINER
Yong Sun <yosun@suse.com>
