." Manpage for qa_test_nfstests.
." Contact Yi Xu <yxu@suse.com> to correct errors or typos.
.TH man 8 "10 Dec 2012" "1.0" "qa_test_nfstests man page"
.SH NAME
qa_test_nfstests
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
The test directories contain programs that can be used to test an implementation of the NFS Protocol.
.br
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
These directories contain programs that can be used to test an implementation of the NFS Protocol. The tests are divided into three groups: 
Basic - basic file system operations tests. General - general file system tests. Special - tests that poke certain common problem areas. Lock - tests that exercise network locking.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://hub.opensolaris.org/bin/view/Community+Group+nfs/tests
.SH AUTHOR
www.connectathon.org
.SH MAINTAINER
Yi Xu <yxu@suse.com>
