#!/bin/bash
# ****************************************************************************
# Copyright (c) 2013 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#sut_timeout 


CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf

rm $TCF_DIR/qa_systemd.tcf

cat >$TCF_DIR/qa_systemd.tcf<<EOF
timer 300
fg 1 check-unit /usr/share/qa/qa_test_systemd/check-unit.sh
wait
EOF

while read line
do
    words=($line)
    service=${words[0]}
    status=${words[1]}
    if test "X${status}" == Xmasked;then
        continue
    fi
    echo $service | egrep '.*@.service$' > /dev/null
    if test $? -eq 0;then
        echo [DEBUG] $service is a pattern
        continue
    fi
    #ignore list
    case $service in
        # have someting with sound hardware
        alsa*) continue;;
        # poweroff is called in this service
        console-shell.service) continue;;
        # services about network
        network.service) continue;;
        sshd.service) continue;;
        wicked*) continue;;
        # services about installation
        YaST2*) continue;;
        # firewall related, they would block the ssh conection.
        SuSEfirewall*) continue;;
        # reboot power related
        systemd-reboot.service) continue;;
        systemd-remount-fs.service) continue;;
        systemd-shutdownd.service) continue;;
        systemd-suspend.service) continue;;
        systemd-hibernate.service) continue;;
        systemd-hybrid-sleep.service) continue;;
        systemd-halt.service) continue;;
        systemd-poweroff.service) continue;;
        systemd-kexec.service) continue;;
        rescue.service) continue;;
        # inird should not be run there
        dracut*) continue;;
        initrd*) continue;;
        # skip plymouth services
        plymouth*.service) continue;;
        # know oneshot service
        # more need to be done with oneshot services
        ntp-wait.service) continue;;
        kexec-load.service) continue;;
        klog.service) continue;;
        purge-kernels.service) continue;;
        sqperf.service) continue;; # qa_testset_performance
        # seems could not stop
        auditd.service) continue;;

    esac
    active_line=$(systemctl status ${service} | egrep '^\s*Active:')
    if test "X${active_line}" == X;then
        echo FAILED systemctl status ${service}
        continue
    fi
    active_words=($active_line)
    cat>/usr/share/qa/qa_test_systemd/${service}.sh<<EOF
#!/bin/bash
source /usr/share/qa/qa_test_systemd/check-service.sh
echo "checking ${service}"
check_the_service ${service} ${active_words[1]}
EOF
    cat>>$TCF_DIR/qa_systemd.tcf<<EOF
fg 1 check_${service} bash /usr/share/qa/qa_test_systemd/${service}.sh
wait
EOF
    done < <(systemctl -l -t service --no-legend --no-pager list-unit-files)


cd $CTCS2_DIR
tools/run $TCF_DIR/qa_systemd.tcf

