SQ_TEST_DIR=/var/log/qaset
SQ_TEST_RUN_DIR=${SQ_TEST_DIR}/runs
SQ_TEST_CALL_DIR=${SQ_TEST_DIR}/calls
SQ_TEST_CONTROL_DIR=${SQ_TEST_DIR}/control
SQ_TEST_LOG_DIR=${SQ_TEST_DIR}/log

SQ_TEST_CONTROL_FILE_PREPARED=${SQ_TEST_CONTROL_DIR}/PREPARED
SQ_TEST_CONTROL_FILE_STOP=${SQ_TEST_CONTROL_DIR}/STOP
SQ_TEST_CONTROL_FILE_DONE=${SQ_TEST_CONTROL_DIR}/DONE
SQ_TEST_CONTROL_FILE_NEXT_RUN=${SQ_TEST_CONTROL_DIR}/NEXT_RUN
SQ_TEST_CONTROL_FILE_SYSTEM_DIRTY=${SQ_TEST_CONTROL_DIR}/SYSTEM_DIRTY

