#!/bin/bash

TARGET_RELEASE=
if test "X${TARGET_RELEASE}" == "X";then
    echo "TARGET_RELEASE is NONE!"
    echo "DO NOTHING then EXIT!!!"
    exit 1
fi

#use the same name for RUN_LIST
RUN_LIST=${TARGET_RELEASE}
CMDABSPATH=$(which $0)
if [ -L $CMDABSPATH ];then
    pushd $(dirname $CMDABSPATH) > /dev/null
    CMDABSPATH=$(readlink $CMDABSPATH)
    popd > /dev/null
fi
pushd $(dirname $CMDABSPATH) > /dev/null
readonly __IMPORT_ROOT=$(pwd)
popd > /dev/null

SQ_SET_BIN=${__IMPORT_ROOT}/sq-set.sh
export SQ_SET_CALL_BY_WRAP=YES
${SQ_SET_BIN} run -t ${TARGET_RELEASE} -s performance -l ${RUN_LIST}
