#!/bin/bash

TARGET_RELEASE=

CMDABSPATH=$(which $0)
if [ -L $CMDABSPATH ];then
    cd $(dirname $CMDABSPATH)
    CMDABSPATH=$(readlink $CMDABSPATH)
fi
cd $(dirname $CMDABSPATH) > /dev/null
COMMONDIR=$(pwd)
cd
echo "COMMONDIR is ${COMMONDIR}"

. ${COMMONDIR}/global.sh

if test ! -d ${SQ_TEST_DIR};then
    mkdir -p ${SQ_TEST_DIR}
    mkdir -p ${SQ_TEST_RUN_DIR}
    mkdir -p ${SQ_TEST_CALL_DIR}
    mkdir -p ${SQ_TEST_CONTROL_DIR}
    mkdir -p ${SQ_TEST_LOG_DIR}
fi

PERF_ALL_BIN=${COMMONDIR}/sq-perf-all
cd ${SQ_TEST_CALL_DIR}

if test "X${TARGET_RELEASE}" == "X";then
    echo "TARGET_RELEASE is NONE!"
    echo "DO NOTHING then EXIT!!!"
    exit 1
fi

screen -L -S SQ_PERL_ALL -d -m "${PERF_ALL_BIN}" ${TARGET_RELEASE}
