#!/bin/bash

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/lib/ctcs2/tcf

NUMCPUS=(grep -c ^processor /proc/cpuinfo)

REAIM_STARTUSERS=1
REAIM_ENDUSERS=$((NUMCPUS*4))
REAIM_INCREMENT=$((NUMCPUS/4))

REAIM_WORKFILE="workfile.disk"

# /abuild is in a reaim config
ABUILD_FS=$(grep '/abuild' /proc/mounts  | awk '{print $3}')
case ${ABUILD_FS} in
    "")
        mkdir -p /abuild
        ABUILD_FS="root"
        ;;
    *)
        echo "[reaim_ioperf] The filesystem on /abuild is ${ABUILD_FS}"
        ;;
esac

TCF_FILE="${TCF_DIR}/reaim_disk_${ABUILD_FS}.tcf"

echo > ${TCF_FILE}
echo "timer 1h" >>${TCF_FILE}
echo "fg 1 reaim-ioperf /usr/lib/reaim/reaim -s ${REAIM_STARTUSERS} -e ${REAIM_ENDUSERS} -i ${REAIM_INCREMENT} -t -r1 -f /usr/lib/reaim/data/${REAIM_WORKFILE}" >> ${TCF_FILE}
echo "wait" >> ${TCF_FILE}

$CTCS2_DIR/tools/run ${TCF_FILE}

#$CTCS2_DIR/tools/run $TCF_DIR/reaim-ioperf.tcf
