#!/bin/bash

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/lib/ctcs2/tcf

NUMCPUS=(grep -c ^processor /proc/cpuinfo)

REAIM_STARTUSERS=1
REAIM_ENDUSERS=$((NUMCPUS*4))
REAIM_INCREMENT=$((NUMCPUS/4))

REAIM_WORKFILE="workfile.alltests"

TCF_FILE="${TCF_DIR}/reaim_disk_all.tcf"
echo > ${TCF_FILE}
echo "fg 1 reaim-ioperf /usr/lib/reaim/reaim -s ${REAIM_STARTUSERS} -e ${REAIM_ENDUSERS} -i ${REAIM_INCREMENT} -t -r1 -f /usr/lib/reaim/data/${REAIM_WORKFILE}" >> ${TCF_FILE}
echo "wait" >> ${TCF_FILE}

cd $CTCS2_DIR
tools/run ${TCF_FILE}
