#!/bin/bash

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/lib/ctcs2/tcf

NUMCPUS=(grep -c ^processor /proc/cpuinfo)

REAIM_STARTUSERS=1
REAIM_ENDUSERS=$((NUMCPUS*4))
REAIM_INCREMENT=$((NUMCPUS/4))

ALL_WORKFILES="workfile.compute workfile.new_dbase workfile.new_fserver workfile.shared workfile.disk workfile.alltests"

REAIM_WORKFILE=

cp ${TCF_DIR}/reaim-ioperf.tcf.tpl ${TCF_DIR}/reaim-ioperf.tcf

for workfile in ${ALL_WORKFILES}; do
    name=${workfile#workfile.}
    echo "fg 1 reaim-${name} /usr/lib/reaim/reaim -s ${REAIM_STARTUSERS} -e ${REAIM_ENDUSERS} -i ${REAIM_INCREMENT} -t -r1 -f /usr/lib/reaim/data/${workfile}" >> ${TCF_DIR}/reaim-ioperf.tcf
    echo "wait" >> ${TCF_DIR}/reaim-ioperf.tcf
done

$CTCS2_DIR/tools/run $TCF_DIR/reaim-ioperf.tcf
