." Manpage for qa_test_evince.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_evince man page"
.SH NAME
qa_test_evince
.SH SYNOPSIS
/usr/share/qa/qa_test_evince/test_evince-run or /usr/share/qa/qa_test_evince/qa_test_evince/evince*.py
.SH TYPE
UI function test
.SH DESCRIPTION
Internal test suite for testing the Evince document viewer based on QA team's test plan #3130.
.br
Scripts are written in Python.
.SH README
qa_test_evince includes 12 automated test cases including: open, rotate, print-preview, save-copy, toolbar, zoom, and more...
.SH OPTIONS
None.
.SH WHAT IT DOES
/usr/share/qa/qa_test_evince/qa_test_evince/evince*.py will be run.
.br
A series of UI tests of Evince will be implemented automatically.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal only.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Calen Chen <cachen@novell.com>
.SH MAINTAINER
Calen Chen <cachen@novell.com>
