#!/bin/sh

export ctcsdir="/usr/lib/ctcs2"
export tcfdir="/usr/share/qa/qa_test_ltp"

# / partition should have at least 20G availble space for all filesystems type testing
av_space=`df -h / |awk '{print $4}' |tail -n 1 |cut -d'G' -f1 |cut -d'.' -f1`

if [ $av_space -le 20 ]; then
	echo "/ partition only have $av_space GB space availble, it need at least 20GB free space"
	exit 1
fi

# some FS packages not default installed
zypper -n in xfsprogs xfsdump xfsprogs-devel xfsprogs-qa-devel jfsutils

# I assume that following directory with the correspoding fs exists:
# /test/growfiles/msdos
mkdir -p /test/growfiles/msdos
# /test/growfiles/reiser
mkdir -p /test/growfiles/reiserfs
# /test/growfiles/ext2
mkdir -p /test/growfiles/ext2
# /test/growfiles/nfs
mkdir -p /test/growfiles/nfs
# /test/growfiles/ramdisk
mkdir -p /test/growfiles/ramdisk
# /test/growfiles/minix
mkdir -p /test/growfiles/vfat
# /test/growfiles/ext3
mkdir -p /test/growfiles/ext3
# /test/growfiles/jfs
mkdir -p /test/growfiles/jfs
# /test/growfiles/xfs
mkdir -p /test/growfiles/xfs
# /test/growfiles/btrfs
mkdir -p /test/growfiles/btrfs

FTYPE='ext2 ext3 ext4 msdos vfat jfs xfs reiserfs btrfs'

# create new fsx tcf for the testing
new_fsx=$tcfdir/tcf/fsx_new.tcf
cp $tcfdir/tcf/fsx.tcf $new_fsx
sed -i '/fsx-reiserfs/d' $new_fsx

# rewrite the testing directory TCtmp to the mounted filesystem
sed -i '/^TCtmp/c TCtmp=$2' /opt/ltp/testcases/bin/fsxtest02
sed -i '/^rm/d' /opt/ltp/testcases/bin/fsxtest02

# prepare FS device
for i in $FTYPE
do
	echo -e "\n###Running fs on $i"
	# create the images, at least 2 GB
	dd if=/dev/zero of=./fs-$i.img bs=1M count=2000
	if [ $i == "reiserfs" ]; then
		echo "y" | mkfs.$i -f fs-$i.img
	else
		echo "y" | mkfs.$i fs-$i.img
	fi
	mount fs-$i.img /test/growfiles/$i -t $i -o loop

        mount |grep "/test/growfiles/$i"
        if [ $? == 1 ]; then
                echo -e "\nSkip $i: failed to mount $i"
                continue
        fi

	export TESTDIR=/test/growfiles/$i
	export TCtmp=$TESTDIR
	echo -e "fg 1 fsx-$i /usr/lib/ctcs2/tools/ltp_wrapper.sh 'export TCbin=\$LTPROOT/testcases/bin;fsxtest02 10000 $TCtmp'\n" >> $new_fsx

	# run fs against each FS type
	new_fs=$tcfdir/tcf/fs_$i.tcf
	cp $tcfdir/tcf/fs.tcf $new_fs
	sed -i '/\$TMPDIR/s/\$TMPDIR/\$TESTDIR/g' $new_fs
	$ctcsdir/tools/run $new_fs

done

mount

# run fsx
echo "###Running fsx"
$ctcsdir/tools/run $new_fsx

# clean
for i in $FTYPE
do
	umount /test/growfiles/$i
	rm -fr /test/growfiles/
	rm -fr ./fs-*
done

FAULT=`dmesg | grep -Ei 'oops|bug|unable to handle|assert|panic|\[<' | grep -v 'swap header version' | grep -v 'filesystem panic'`
if [ x"$FAULT" != "x" ] ; then
	echo "++ Something found while fs..."
	echo "$FAULT !"
	exit -1
fi
