." Manpage for qa_test_subversion.
.TH man 8 "15 Jul 2013" "0.1.0" "qa_test_subversion man page"
.SH NAME
qa_test_subversion
.SH SYNOPSIS
/usr/share/qa/tools/test_subversion-run
.SH TYPE
test suite
.SH DESCRIPTION
Test basic subversion capability (import, checkout, commit)
.br
over several transports (dav, dav+auth, ssh, dav+authz)
.SH README
None.
.SH OPTIONS
see svn.sh -h
.br
.SH COMMON PROBLEMS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
http://qam.suse.de
.SH AUTHOR
Yuri Tsarev <ytsarev@suse.com> - original coding
.br
Jan Matejka <jmatejka@suse.cz> - rewrite for full automation
.SH MAINTAINER
Jan Matejka <jmatejka@suse.cz>
