#!/bin/bash

MAKE_TARGET=rerun

case "$1" in
    bcopy)
        MAKE_TARGET=rerun_bcopy
        ;;
    connect)
        MAKE_TARGET=rerun_connect
        ;;
    ctx)
        MAKE_TARGET=rerun_ctx
        ;;
    file)
        MAKE_TARGET=rerun_file
        ;;
    http)
        MAKE_TARGET=rerun_http
        ;;
    mem)
        MAKE_TARGET=rerun_mem
        ;;
    mmap)
        MAKE_TARGET=rerun_mmap
        ;;
    ops)
        MAKE_TARGET=rerun_ops
        ;;
    pagefault)
        MAKE_TARGET=rerun_pagefault
        ;;
    pipe)
        MAKE_TARGET=rerun_pipe
        ;;
    proc)
        MAKE_TARGET=rerun_proc
        ;;
    rpc)
        MAKE_TARGET=rerun_rpc
        ;;
    select)
        MAKE_TARGET=rerun_select
        ;;
    sig)
        MAKE_TARGET=rerun_sig
        ;;
    syscall)
        MAKE_TARGET=rerun_syscall
        ;;
    tcp)
        MAKE_TARGET=rerun_tcp
        ;;
    udp)
        MAKE_TARGET=rerun_udp
        ;;
    unix)
        MAKE_TARGET=rerun_unix
        ;;
    *)
        MAKE_TARGET=rerun
        ;;
esac

cd /usr/share/qa/qa_test_lmbench/results
if [ -d *linux-gnu ] ; then rm -r *linux-gnu ; fi
cd /usr/share/qa/qa_test_lmbench/src
#make rerun; make rerun; make rerun;
make clobber 2>&1 >/dev/null
make ${MAKE_TARGET} 2>&1 >/dev/null
cd /usr/share/qa/qa_test_lmbench/results
#find . -type d -maxdepth 1 | while read dirname;do
#  case ${dirname} in
#      *linux-gnu)
#         echo "Find Dir ${dirname}";;
#      *) continue
#  esac
#      cat ${dirname}/$(hostname).*
#done
make 
