#!/bin/bash

MAKE_TARGET=rerun

case "$1" in
    bcopy)
        MAKE_TARGET=rerun_bcopy
        ;;
    ctx)
        MAKE_TARGET=rerun_ctx
        ;;
    file)
        MAKE_TARGET=rerun_file
        ;;
    mem)
        MAKE_TARGET=rerun_mem
        ;;
    ops)
        MAKE_TARGET=rerun_ops
        ;;
    local_comm)
        MAKE_TARGET=rerun_local_comm
        ;;
    syscall)
        MAKE_TARGET=rerun_syscall
        ;;
    *)
        MAKE_TARGET=rerun
        ;;
esac

cd /usr/share/qa/qa_test_lmbench/results
if [ -d *linux-gnu ] ; then rm -r *linux-gnu ; fi
cd /usr/share/qa/qa_test_lmbench/src
#make rerun; make rerun; make rerun;
make clobber 2>&1 >/dev/null
make ${MAKE_TARGET} 2>&1 >/dev/null
cd /usr/share/qa/qa_test_lmbench/results
#find . -type d -maxdepth 1 | while read dirname;do
#  case ${dirname} in
#      *linux-gnu)
#         echo "Find Dir ${dirname}";;
#      *) continue
#  esac
#      cat ${dirname}/$(hostname).*
#done
make 
