." Manpage for qa_test_memtester.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_memtester man page"
.SH NAME
qa_test_memtester
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
RD-QA-Kernel internal tool for intensive memory tests.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://pyropus.ca/software/qa_test_memtester
.SH AUTHOR
Charles Cazabon <memtest@discworld.dyndns.org>
.SH MAINTAINER
Erik Hamera <erik.hamera@novell.com>
