." Manpage for qa_test_apparmor-profiles.
." Contact Jia Li <jli@suse.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_apparmor-profiles-profiles man page"
.SH NAME
qa_test_apparmor-profiles
.SH SYNOPSIS
/usr/share/qa/tools/test_apparmor-profiles-run
.SH TYPE
function test
.SH DESCRIPTION
This suite contains apparmor-profile.
.br
"apparmor-profile" focuses on profile testing, like: apache, tcp commands (ping, traceroute).
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Various functions will be tested, include: apache, tcp commands (ping, traceroute).
.SH COMMON PROBLEMS
None.
.SH WARNINGS
Make sure "Novell AppArmor" pattern has already be installed in SUT.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Looks like this was written internally, but it's got GPL written throughout and I found the source published out on apparmor.sourcearchive.com, so keeping GPL v2 for now. The source is packaged and there are 7 patches added.
.SH LICENSE
GPL v2
.SH UPSTREAM
None.
.SH AUTHOR
Jone Doe <jli@suse.com>
.SH MAINTAINER
Yong Sun <yosun@suse.com>
