#!/bin/bash
#sut_timeout 12000

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf
LOG_DIR=/usr/share/qa/qa_test_siege/siege/var

INITSCRIPT=/etc/init.d/apache2
if [ ! -f $INITSCRIPT ]
then
    INITSCRIPT=/etc/init.d/apache
fi

if [ ! -f $INITSCRIPT ]
then
    echo "Cannot find Apache initscript"
    exit 1
fi

if $INITSCRIPT status > /dev/null
then
    $INITSCRIPT stop
fi

$INITSCRIPT start -D SSL -D SSL_DEFAULT_VHOST

/etc/init.d/cron stop

if [ $HOSTTYPE = i386 ]; then
    ulimit -s 128
fi


if [ ! -f ~/.siegerc ]
then
	cp /usr/share/qa/qa_test_siege/.siegerc ~/
fi

if [ ! -d $LOG_DIR ]; then
	mkdir $LOG_DIR
fi

# Fixed the issue of socket cannot assign requested address
tw_reuse_default=`cat /proc/sys/net/ipv4/tcp_tw_reuse`
if [ $tw_reuse_default -eq 0 ]; then
	echo 1 >/proc/sys/net/ipv4/tcp_tw_reuse
fi

# Run test
if echo $1 | grep https > /dev/null
then
    $CTCS2_DIR/tools/run $TCF_DIR/qa_siege_https.tcf
elif echo $1 | grep performance > /dev/null
then
    $CTCS2_DIR/tools/run $TCF_DIR/qa_siege_performance.tcf
else
    $CTCS2_DIR/tools/run $TCF_DIR/qa_siege_http.tcf
fi

# Clean setup
echo $tw_reuse_default >/proc/sys/net/ipv4/tcp_tw_reuse
