#!/bin/bash
# ****************************************************************************
# Copyright (c) 2013 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#


export LANG=C

function usage() {
	echo ""
	echo "Usage: $0 [step]"
	echo "       step can only be 01/02/03/04, default to 01 if not set."
}

step=$1
[ -z "$step" ] && step="01"
if [ "$step" != "01" -a "$step" != "02" -a "$step" != "03" -a "$step" != "04" ] || [ $# -ne 1 -a $# -ne 0 ];then
	usage
	exit 1
fi

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf
RUN_NAME=`basename $0`
TCF_NAME=${RUN_NAME/run/${step}}".tcf"
TCF_FILE="$TCF_DIR/$TCF_NAME"

rm -rf /tmp/virt_screenshot.tar.bz2 /tmp/virt-install_screenshot

$CTCS2_DIR/tools/run $TCF_FILE

rm /tmp/virt_screenshot.tar.bz2
[ -d /tmp/virt-install_screenshot/ ] && tar jcf /tmp/virt_screenshot.tar.bz2 /tmp/virt-install_screenshot/

returncode=0

for file in `find /var/log/qa/ctcs2/ -name test_results`; do
	[ -z "$(cat $file)" ] && ((returncode+=1))
done

((returncode+=`find /var/log/qa/ctcs2/ -name test_results -exec grep "^[0-9] 0" {} \; | wc -l`))

v_updir=`find /var/log/qa/ctcs2 -type d -name "test-VH-Upgrade*"|tail -1`
[ -d $v_updir -a -e /tmp/virt_screenshot.tar.bz2 ] && cp /tmp/virt_screenshot.tar.bz2 $v_updir/

#upload virtualization debug log
tar cvf $v_updir/libvirt.tar /var/log/libvirt
cp /var/log/messages $v_updir/
if uname -r | grep -iq xen && [ -d /var/log/xen ];then
	tar cvf $v_updir/xen-log.tar /var/log/xen
fi

/usr/share/qa/tools/remote_qa_db_report.pl -b -c "Test result for virtualization host upgrade step $step test: $TCF_FILE."

exit $returncode
