." Manpage for qa_test_cpio.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_cpio man page"
.SH NAME
qa_test_cpio
.SH SYNOPSIS
/usr/share/qa/qa_test_cpio/test_cpio-run
.SH TYPE
function test
.SH DESCRIPTION
This suite will test archive functions of cpio command.
.SH README
Data files included from other Suse authors.
.SH OPTIONS
None.
.SH WHAT IT DOES
Two directories will be created for archives and unpacked in different formats, and then each peer will be compared automatically.
.SH COMMON PROBLEMS
None, because this package will not cause serious trouble.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. No licence provided in the sources. Internal development. Meant to be GPL.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
http://www.clamav.net/
.SH AUTHOR
Katarina Machalkova <kmachalkova@suse.cz>; Data files included from other Suse authors.
.SH MAINTAINER
Nathan Zhao <jtzhao@suse.com>
