." Manpage for qa_test_process_stress.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_process_stress man page"
.SH NAME
qa_test_process_stress
.SH SYNOPSIS
/usr/share/qa/tools/test_process_stress-run
.SH TYPE
Stress test for processes.
.SH DESCRIPTION
One of the validation test cases, which focuses on process stress testing.
.SH README
None. 
.SH OPTIONS
None
.SH WHAT IT DOES
Run "/opt/ltp/testcases/bin/process -b 5 -d 3" 600 times.
.SH COMMON PROBLEMS
None
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
License: GPL v2 or later. Spec file license: GPL v2 or later.
.SH UPSTREAM
None.
.SH AUTHOR
Yi Xu <yxu@novell.com>
.SH MAINTAINER
csxia@novell.com
