." Manpage for qa_test_libo.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_libo man page"
.SH NAME
qa_test_libo
.SH SYNOPSIS
None.
.SH TYPE
None.
.SH DESCRIPTION
This is a qa_test_libo test package that can be used to test libreoffice through testtool.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Yifan Jiang <yfjiang@novell.com>
.SH MAINTAINER
None.
