#!/bin/bash
# ****************************************************************************
# Copyright (c) 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#

#
## 1. generate testcases
#cd qa_test_virtualization
#./_generate_install.sh -d "../../../libs/qa_lib_virtauto-data/qa_lib_virtauto-data/autoinstallation"
##./_generate_install.sh -d "../../virtautolib/virtautolib/data/autoinstallation" -t "tap:aio"
##./_generate_install.sh -d "../../virtautolib/virtautolib/data/autoinstallation" -t "tap:qcow2"
#cd - > /dev/null
#
## 2. generate tcfs
#./_generate_tcf.sh standalone > qa_virtualization-standalone.tcf 
#./_generate_tcf.sh network > qa_virtualization-network.tcf 
#
#./_generate_sles10sp4supported_tcf.sh standalone > qa_virtualization-sles10sp4supported-standalone.tcf 
#./_generate_sles10sp4supported_tcf.sh network > qa_virtualization-sles10sp4supported-network.tcf 
#
#./_generate_sles11sp1supported_tcf.sh standalone > qa_virtualization-sles11sp1supported-standalone.tcf 
#./_generate_sles11sp1supported_tcf.sh network > qa_virtualization-sles11sp1supported-network.tcf 
#
## 3. pack
#version=`grep ^Version: qa_test_virtualization.spec | awk {'print $2'}`
tar cjf qa_test_virtualization.tar.bz2 qa_test_virtualization
tar cjf generate.tar.bz2 generate
tar cjf tools.tar.bz2 tools

