." Manpage for qa_test_virtualization.
." Contact David Mulder <dmulder@suse.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_virtualization man page"
.SH NAME
qa_test_virtualization
.SH SYNOPSIS
/usr/share/qa/tools/virtualization-*-run
.SH TYPE
function test
.SH DESCRIPTION
This is a test of XEN and KVM virtualization.
.br
It contains installation tests of many OSes.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Various virtual machines with different OSes and virtualization types are installed.
.SH COMMON PROBLEMS
The installation sources for OSes are not written in config file correctly.
.SH WARNINGS
The host must already be set-up as XEN or KVM virtualization host.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Lukas Lipavsky <llipavsky@suse.cz>
.SH MAINTAINER
Lukas Lipavsky <LLipavsky@suse.com>
Arthur Guo <AGuo@suse.com>
