." Manpage for qa_nmon.
." Contact Yi Xu <yxu@suse.com> to correct errors or typos.
.TH man 8 "10 Dec 2012" "1.0" "qa_nmon man page"
.SH NAME
qa_nmon
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
A free tool to analyze AIX and Linux performance
.br
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
The nmon tool is designed for AIX and Linux performance specialists to use for monitoring and analyzing performance data, including:
CPU utilization
Memory use
Kernel statistics and run queue information
Disks I/O rates, transfers, and read/write ratios
Free space on file systems
Disk adapters
Network I/O rates, transfers, and read/write ratios
Paging space and paging rates
CPU and AIX specification
Top processors
IBM HTTP Web cache
User-defined disk groups
Machine details and resources
Asynchronous I/O -- AIX only
Workload Manager (WLM) -- AIX only
IBM TotalStorage® Enterprise Storage Server® (ESS) disks -- AIX only
Network File System (NFS)
Dynamic LPAR (DLPAR) changes -- only pSeries p5 and OpenPower for either AIX or Linux
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://www.ibm.com/developerworks/aix/library/au-analyze_aix/
.SH AUTHOR
IBM
.SH MAINTAINER
Yi Xu <yxu@suse.com>
