." Manpage for qa_test_yast2.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_yast2 man page"
.SH NAME
qa_test_yast2
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
An internal YaST2 test suite. It uses the open-source xmacro tool to function.
.SH README
qa_test_yast2 includes a test for the YaST online updater, however, we are currently planning an improved YaST testsuite for testing many of our other YaST modules.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal (partially), no patches.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
None.
.SH AUTHOR
Frank <fseidel@suse.de>
.SH MAINTAINER
Lukas Lipavsky <LLipavsky@novell.com>
