." Manpage for qa_test_sample.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_sample man page"
.SH NAME
qa_test_sample
.SH SYNOPSIS
Intended to be a package template
.br
/usr/share/qa/qa_test_sample/test_sample-run
.SH TYPE
qa_ package example.
.SH DESCRIPTION
This is a sample qa_ test package that can be used as a template to create other packages or just for training purposes.
.br
qa_test_sample_test* scripts are writen by Shell, Perl and Python.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
qa_test_sample_testone.sh, qa_test_sample_testtwo.pl and qa_test_sample_testthree.py will be implemented.
.br
A directory called "/thisdir" will be created if it doesn't exist, and a message of creation result will be printed.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
No harm scripts, generally no problem.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
SUSE Proprietary.
.SH UPSTREAM
None. 
.SH AUTHOR
Dan Collingridge <dcollingridge@novell.com>
.SH MAINTAINER
Arthur Guo <aguo@novell.com>
