#!/bin/sh
TCF_FILE=/usr/share/qa/tcf/libmicro-memory.tcf
CTCS2_DIR=/usr/lib/ctcs2

cat <<EOF >> ${TCF_FILE}
timer 3600
fg 1 libmicro-memory /usr/lib/libMicro/bin/bench_memory.sh
wait
EOF

$CTCS2_DIR/tools/run ${TCF_FILE}

