#!/bin/sh
TCF_FILE=/usr/share/qa/tcf/libmicro-process.tcf
CTCS2_DIR=/usr/lib/ctcs2

cat <<EOF >> ${TCF_FILE}
timer 3600
fg 1 libmicro-process /usr/lib/libMicro/bin/bench_process.sh
wait
EOF

$CTCS2_DIR/tools/run ${TCF_FILE}

