#!/bin/sh
TCF_FILE=/usr/share/qa/tcf/libmicro-contextswitch.tcf
CTCS2_DIR=/usr/lib/ctcs2

cat <<EOF >> ${TCF_FILE}
timer 3600
fg 1 libmicro-contextswitch /usr/lib/libMicro/bin/bench_contextswitch.sh
wait
EOF

$CTCS2_DIR/tools/run ${TCF_FILE}
