." Manpage for qa_test_sysbench.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_sysbench man page"
.SH NAME
qa_test_sysbench
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
This benchmark was designed for identifying basic system parameters, as they are important for systems using MySQL (w Innodb) under intensive load.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, 4 patches.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://sysbench.sourceforge.net/
.SH AUTHOR
Alexey Kopytov (alexeyk@mysql.com), Konstantin Osipov (rabidtransit@users.sourceforge.net), Patrick Kirsch <pkirsch@suse.de>
.SH MAINTAINER
Kathy Li <jli@suse.com>
