." Manpage for qa_test_samba.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_samba man page"
.SH NAME
qa_test_samba
.SH SYNOPSIS
/usr/share/qa/tools/test_samba-run
.SH TYPE
test suite
.SH DESCRIPTION
Internal test suite for testing samba.
.SH README
qa_test_samba includes 8 automated test cases including: daemon start/stop, user management, shares (guest), shares (non-guest), PID file handling, smbcontrol, file access, file access (ACL).
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None
.SH WARNINGS
Don't press Ctrl-C while testing run
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
http://www.php.net
.SH AUTHOR
Lukas <llipavsky@suse.cz>
.SH MAINTAINER
Leon Wang <llwang@novell.com>
