#!/bin/bash
# create specific guest images
#
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

echo "Creating guest images"

DIR=$(dirname `readlink -f $0`)
. $DIR/../testing.conf
. $DIR/function.sh

HOSTSDIR=$DIR/../hosts


mkdir -p $IMGDIR
mkdir -p $LOOPDIR

pushd $IMGDIR
for image_url in ${SLE_IMAGE_URLS}
do
	log_action "Getting image $image_url"
	echo $image_url     
	execute "curl -L -O $image_url"
done
popd
