." Manpage for qa_test_llcbench.
." Contact JYao <jyao@suse.com> to correct errors or typos.
.TH man 8 "21 Oct 2012" "1.0" "qa_test_llcbench man page"
.SH NAME
qa_test_llcbench
.SH SYNOPSIS
Intended to be a package template
.br
/usr/share/qa/qa_test_llcbench/test_llcbench-run
.SH TYPE
qa_test_llcbench package llcbench.
.SH DESCRIPTION
This is a qa test package that can be used as a template to create other packages or just for training purposes.
.br
qa_test_llcbench_test* scripts are writen by Shell, Perl and C.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
blasbench and mpbench will be implemented.
.br
A directory called "/thisdir" will be created if it doesn't exist, and a message of creation result will be printed.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
No harm scripts, generally no problem.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Jia Yao <jyao@suse.com>
.SH MAINTAINER
Jia Yao <jyao@suse.com>
