#! /bin/sh
# Copyright (c) 1995-2003 SuSE Linux AG, Nuernberg, Germany.
# All rights reserved.
#
# Author: Lance Wang
#
# /etc/init.d/qaset
#
### BEGIN INIT INFO
# Provides:       qaset
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: qaset service
# Description:  Used by ACAPII team
### END INIT INFO
. /etc/rc.status
rc_reset

QASET_SERVISE_BIN=/usr/share/qa/qaset/qaset-service

case "$1" in
  start)
    startproc ${QASET_SERVISE_BIN}
    rc_status -v
    ;;
  stop)
    echo "No need to stop"
    ;;
  restart)
    echo "No need to restart"
    ;;
esac
rc_exit
