." Manpage for qa_test_fs_stress.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_fs_stress man page"
.SH NAME
qa_test_fs_stress
.SH SYNOPSIS
/usr/share/qa/tools/test_fs_stress-run
.SH TYPE
Internal file system stress test.
.SH DESCRIPTION
qa_test_fs_stress is one of the validation test cases, which focuses on file system stress tests. It runs numerous medium and large file copies in parallel with MD5sum integrity checks.
.SH README
None. 
.SH OPTIONS
None
.SH WHAT IT DOES
Keeps on pressing file system by copying files synchronously.
.SH COMMON PROBLEMS
None
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
License: GPL v2. Spec file license: GPL v2 or later.
.SH UPSTREAM
None.
.SH AUTHOR
Yi Xu <yxu@novell.com>, Olli Ries
.SH MAINTAINER
csxia@novell.com
