." Manpage for qa_test_features.
." Contact QA Automation Team <qa-automation@suse.de> to correct errors or typos.
.TH man 8 "25 Sep 2013" "1.0" "qa_test_features man page"
.SH NAME
qa_test_features
.SH SYNOPSIS
Package that contains testcases for individual features of our products (if they 
are not part of existing tetstuites)
.br
/usr/share/qa/qa_test_features/test_features-sle12-run
.SH TYPE
SLE features testcases for TDD.
.SH SEE ALSO
http://portal.qa.suse.cz
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Lukas Lipavsky <llipavsky@suse.com>
.SH MAINTAINER
QA Automation Team <qa-automation@suse.de>

