." Manpage for qa_test_sharutils.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_sharutils man page"
.SH NAME
qa_test_sharutils
.SH SYNOPSIS
upstream_wrapper.sh [option]
.SH TYPE
Function test suite
.SH DESCRIPTION
Tests from sharutils package (source code) included as well as one custom testcase for uuencode/decode.
.br
GNU shar makes so-called shell archives out of many files, preparing them for transmission by electronic mail services. A shell archive is a collection of files that can be unpacked by /bin/sh. A wide range of features provide extensive flexibility in manufacturing shars and in specifying shar smartness. For example, shar may compress files, uuencode binary files, split long files and construct multi-part mailings, ensure correct unsharing order, and provide simplistic checksums.
.SH README
None. 
.SH OPTIONS
Uuen/Uudecode
.SH WHAT IT DOES
shar may compress files, uuencode binary files.
.SH COMMON PROBLEMS
None
.SH WARNINGS
Implement this test suite through hamsta.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, 1 patch.
.SH LICENSE
License: GPL v2 or later. Spec file license: GPL.
.SH UPSTREAM
http://qa.suse.de/
.SH AUTHOR
gnu.org <gnu.org>
.SH MAINTAINER
Jerry Tang  <jtang@novell.com>
