." Manpage for qa_test_openssl.
." Contact Vít Pelčák <vpelcak@suse.com> to correct errors or typos.
.TH man 8 "26 Oct 2011" "1.0" "qa_test_openssl man page"
.SH NAME
qa_test_openssl
.SH SYNOPSIS
/usr/share/qa/tools/test_openssl-run
.SH TYPE
Function test of openssl.
.SH DESCRIPTION
Runs upstream tests pf p[emss;.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
A series of tests will be executed and resuts will be provided.
.SH COMMON PROBLEMS
There should be no trouble running these tests.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code and upstream unit tests. Upstream unit tests licensed under openssl license. Our code under GPL.
.SH LICENSE
Main openssl tarball: OpenSSL Open Source License; Our stuff: GPL v3 or later
.SH UPSTREAM
None.
.SH AUTHOR
Tomáš Chvátal <tchvatal@suse.com>
.SH MAINTAINER
Vít Pelčák <vpelcak@suse.com>
