." Manpage for qa_test_tomboy.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_tomboy man page"
.SH NAME
qa_test_tomboy
.SH SYNOPSIS
/usr/share/qa/qa_test_tomboy/test_tomboy-runi
.br
/usr/share/qa/qa_test_tomboy/qa_test_tomboy/tomboy*.py
.SH TYPE
UI function test
.SH DESCRIPTION
Tomboy is a desktop note-taking application for Linux, Unix, Windows and Mac OS X. It is simple and easy to use.
.br
A series of tests for Tomboy application based on QA team's test plan #3130.
.br
Scripts are written in Python.
.SH README
None. 
.SH OPTIONS
None
.SH WHAT IT DOES
/usr/share/qa/qa_test_tomboy/qa_test_tomboy/tomboy*.py will be run.
.br
A series of UI tests of Tomboy will be implemented automatically.
.SH COMMON PROBLEMS
None
.SH WARNINGS
None
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. No licence provided in the sources. Internal development. Meant to be GPL.
.SH LICENSE
License: n/a. Spec file license: GPL.
.SH UPSTREAM
http://qa.suse.de
.SH AUTHOR
Calen Chen <cachen@novell.com>
.SH MAINTAINER
Calen Chen <cachen@novell.com>
