#!/bin/bash
username=`who |grep :0 | head -n 1 |awk {'print $1'}`

comments="
export DISPLAY=:0.0
killall gnome-panel
sleep 5
killall -9 /usr/lib/at-spi/at-spi-registryd tomboy-panel tomboy
sh -c \"/usr/lib/at-spi/at-spi-registryd&\"
sleep 3
eval \`dbus-launch --sh-syntax&\`
sleep 3
/usr/lib/ctcs2/tools/run /usr/share/qa/tcf/qa_tomboy.tcf"

if [ "$username" != "$USER" ]; then
	su - $username -c "$comments"
	cp -r `getent passwd $username | cut -d: -f 6`/var-log-qa/* /var/log/qa
	su - $username -c "cd; rm -fr var-log-qa"
else
	sh -c "$comments"
fi

