#!/bin/bash
export LANG=C
export DISPLAY=:0.0
xhost +
killall /usr/lib/at-spi/at-spi-registryd tomboy
[ `ps aux | grep at-spi-registry | wc -l` -gt 1 ] || /usr/lib/at-spi/at-spi-registryd&
/usr/lib/ctcs2/tools/run /usr/share/qa/tcf/qa_tomboy.tcf
