." Manpage for qa_test_findutils.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_findutils man page"
.SH NAME
qa_test_findutils
.SH SYNOPSIS
/usr/share/qa/tools/test_findutils-run
.SH TYPE
Function test
.SH DESCRIPTION
qa_test_findutils is a test suite that verify functions of command "find".
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Run scripts like: findutils_find.sh, findutils_xarg.sh, xargs_orig.sh, and find_orig.sh, to cover kinds of "find" functions.
.SH COMMON PROBLEMS
This suite is for SLES11, and won't be installed if the SUT is SLES10.
.SH WARNINGS
Make sure the platform is SLES11.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Looks like an external testsuite to which we may have added 1 or 2 tests.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
None.
.SH AUTHOR
findutils <bug-findutils@gnu.org>, Katarina
.SH MAINTAINER
Jerry Tang <jtang@novell.com>
