." Manpage for qa_test_lmbench.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_lmbench man page"
.SH NAME
qa_test_lmbench
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
qa_test_lmbench is a series of micro benchmarks intended to measure basic operating system and hardware system metrics.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, 2 patches.
.SH LICENSE
License: GPL v2 or later. Spec file license: GPL v2 or later. Cannot distribute results openly if benchmark has been modified, so would need to contribute patches back to the original project, or just start our own.
.SH UPSTREAM
http://www.bitmover.com/qa_test_lmbench/
.SH AUTHOR
Larry McVoy <lm@who.net>, Yi Xu
.SH MAINTAINER
Vilem Marsik <VMarsik@novell.com>
