." Manpage for qa_test_lha.
." Contact Zdenek Kubala <zkubala@suse.com> to correct errors or typos.
.TH man 8 "3 Aug 2016" "1.0" "qa_test_lha man page"
.SH NAME
qa_test_lha
.SH SYNOPSIS
None.
.SH TYPE
None.
.SH DESCRIPTION
Testcases for lha package. This is a light test suite, which focuses on options and commands test. 
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
SUSE Internal
.SH UPSTREAM
None.
.SH AUTHOR
Zdenek Kubala <zkubala@suse.com>
.SH MAINTAINER
Zdenek Kubala <zkubala@suse.com>
