." Manpage for qa_test_bash.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_bash man page"
.SH NAME
qa_test_bash
.SH SYNOPSIS
/usr/share/qa/qa_test_bash/test_bash-run
.SH TYPE
function test
.SH DESCRIPTION
Internal test suite for testing various components and capabilities of the bash shell.
.SH README
qa_test_bash includes 61 automated test cases including: alias, braces, dollars, func, jobs, posix, printf, and more... 
.SH OPTIONS
None.
.SH WHAT IT DOES
A series of test cases which cover 60 aspects of bash functionality.
.SH COMMON PROBLEMS
None, because this package will not cause serious trouble.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Scripts from us.
.SH LICENSE
License: GPL v2 or later. Spec file license: GPL v2 or later. Written for internal use only by Klara Cihlarova, but some data files included are GPL and open-sourced by Bash.
.SH UPSTREAM
http://httpd.apache.org/test/
.SH AUTHOR
Klara Cihlarova <cihlarov@novell.com>
.SH MAINTAINER
Arthur Guo <aguo@novell.com>
