#!/bin/sh
#sut_timeout 3600

# run tiobench.pl with some good standard parameters
CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf

TCF=${TCF_DIR}/tiobench-basic.tcf
echo 'fg 1 tiobench-basic /usr/share/qa/qa_test_tiobench/abuildinfo' > ${TCF}
NR_CPU=$(grep -c '^processor' /proc/cpuinfo)
MEM_SIZE=$(grep 'MemTotal:' /proc/meminfo | awk '{print $2}')

for block in 4096 32768; do
    for num in 1 2;do
        NR_THREAD=$((${NR_CPU} * ${num}))
        FILE_SIZE=$((${MEM_SIZE} * 2 / ${NR_THREAD} / 1024)) #in MiB
        cat <<EOF >> ${TCF}
fg 1 tiobench-basic-{block}-${num} tiobench.pl --size ${FILE_SIZE} --block ${block} --threads ${NR_THREAD} --dir /abuild
EOF
    done
done

echo 'wait' >> ${TCF}

$CTCS2_DIR/tools/run ${TCF}
