." Manpage for qa_test_rugg.
." Contact Yi Xu <yxu@suse.com> to correct errors or typos.
.TH man 8 "07 Mar 2013" "1.0" "qa_test_rugg man page"
.SH NAME
qa_test_rugg
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Rugg is a hard drive and filesystem harness tool that allows you to test and benchmark drives and filesystems, by writing simple to complex scenarios that can mimic the behaviour of real-world applications.
.br
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
test and benchmark drives and filesystems
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
GPL v3 or later
.SH UPSTREAM
http://rugg.sourceforge.net/index.html
.SH AUTHOR
NLANR/DAST
.SH MAINTAINER
Yi Xu <yxu@suse.com>
