ifdef QA_TEST_DELETE_IT
ccflags-y += -DQA_TEST_TO_BE_DELETED
endif

obj-m += qa-kgr-patch-sys-getpid.o
obj-m += qa-kgr-patch-sys-read.o
obj-m += qa-kgr-patch-sys-write.o
obj-m += qa-kgr-patch-sys-fsync.o
