." Manpage for qa_test_xfstests.
.TH man 8 "21 Dec 2013" "1.0" "qa_test_xfstests man page"
.SH NAME
qa_test_xfstests
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
The filesystem regression test suite.  Includes support for acl, attr, dmapi,
ext2/3/4, xfs, udf, reiserfs, nfs, btrfs testing.  Contains around 300+
specific tests for userspace & kernelspace.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
Artistic (include copyright notice and disclaimer as described in the source).
.SH UPSTREAM
n/a
.SH AUTHOR
dsterba@suse.cz
.SH MAINTAINER
None.
