#!/bin/sh
# ****************************************************************************
# Copyright © 2011 Unpublished Work of SUSE, Inc. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE, INC.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************

# This is just for the record.
# This test is not run.

exit 0

cat <<\EOF

Prior to 5.0.91, ...

The problem:
  On a VFAT file system with coreutils-5.0.90, `mv FOO foo' removes the
  sole copy of the file named by both the source and destination arguments.

Demonstrate the problem, as root:

cd /tmp                                    \
  && dd if=/dev/zero of=1 bs=8192 count=50 \
  && mkdir mnt && mkfs -t vfat 1           \
  && mount -oloop 1 mnt && cd mnt          \
  && printf something important > foo      \
  && mv foo FOO
test -f FOO && echo PASS-1 || echo FAIL-1
ln foo bar
mv foo FOO
test -f FOO && echo PASS-2 || echo FAIL-2

And in case you actually do the above, you can do this to clean up:

  cd /tmp && umount /tmp/mnt && rm -r 1 mnt

Hey!  Can't create hard links on vfat.
The above `ln' evokes an `operation not permitted' failure.

This demonstrates the same thing with file system type `umsdos'
No hard links:

cd /tmp                                    \
  && dd if=/dev/zero of=1 bs=8192 count=50 \
  && mkdir mnt && mkfs -t msdos 1          \
  && mount -t umsdos -oloop 1 mnt && cd mnt \
  && printf something important > foo      \
  && mv foo FOO
test -f FOO && echo PASS-1 || echo FAIL-1
ln foo bar
mv foo FOO
test -f FOO && echo PASS-2 || echo FAIL-2

EOF

