." Manpage for qa_test_apache_testsuite.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_apache_testsuite man page"
.SH NAME
qa_test_apache_testsuite
.SH SYNOPSIS
/usr/share/qa/tools/test_apache_testsuite-run
.SH TYPE
test suite.
.SH DESCRIPTION
This package contains automated tests for apache developed with perl-framework.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None
.SH WARNINGS
Don't press Ctrl-C while testing run.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, 1 patch.
.SH LICENSE
Apache 2.0
.SH UPSTREAM
None.
.SH AUTHOR
Martin Mrazik <mmrazik@suse.cz>
.SH MAINTAINER
Nathan Zhao <jtzhao@suse.com>
