#!/bin/bash

cd `dirname $(readlink -f $0)`

. libo_conf
. libo_logging

function killlibotest(){

    selfpid=$$
    log "Kill running libotest related processes if any..."
    kill -9 `ps aux | grep -e libreoffice -e testtool -e libo -e soffice.bin | grep -v -e grep -e $selfpid | awk '{print $2}'` > /dev/null 2>&1

}

cmd=$1; shift

scripts=0
build=0

while getopts t:b: o; do
    case $o in
        t)scripts="$OPTARG";;
        b)build="$OPTARG";;        
    esac
done

if test "$cmd" = "run"; then
    killlibotest
    su $user -c "./libo_run $build \"$scripts\""
elif test "$cmd" = "download"; then
    su $user -c "./libo_download $build"
elif test "$cmd" = "install"; then
    killlibotest
    su $user -c "./libo_install"
elif test "$cmd" = "clean"; then
    killlibotest
    su $user -c "./libo_clean"
else
    logwarning 'Need args: run [$build] / download $build / install / clean'
fi
