#!/bin/bash
# ****************************************************************************
# Copyright © 2013 Unpublished Work of SUSE, Inc. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE, INC.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************

cd `dirname $(readlink -f $0)`

. libo_conf
. libo_logging

function killlibotest(){

    selfpid=$$
    log "Kill running libotest related processes if any..."
    kill -9 `ps aux | grep -e libreoffice -e testtool -e libo -e soffice.bin | grep -v -e grep -e $selfpid | awk '{print $2}'` > /dev/null 2>&1

}

cmd=$1; shift

scripts=0
build=0

while getopts t:b: o; do
    case $o in
        t)scripts="$OPTARG";;
        b)build="$OPTARG";;        
    esac
done

if test "$cmd" = "run"; then
    killlibotest
    su $user -c "./libo_run $build \"$scripts\""
elif test "$cmd" = "download"; then
    su $user -c "./libo_download $build"
elif test "$cmd" = "install"; then
    killlibotest
    su $user -c "./libo_install"
elif test "$cmd" = "clean"; then
    killlibotest
    su $user -c "./libo_clean"
else
    logwarning 'Need args: run [$build] / download $build / install / clean'
fi

