#!/bin/bash
# ****************************************************************************
# Copyright © 2011 Unpublished Work of SUSE, Inc. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE, INC.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf
SLEPOS_LIB=/root/slepos_lib.sh
CONF_PATH=/usr/share/qa/qa_test_slepos

if [ -f /root/qa_slepos-local_config.sh ]; then
	source /root/qa_slepos-local_config.sh
elif [ -f "$CONF_PATH"/local_config.sh ]; then
	source "$CONF_PATH"/local_config.sh
else
	echo "Local configuration wasn't found, exiting"
	exit 2
fi

if [ "$CONFIG_EDITED" = no ]; then
	echo "Edit local configuration first, please."
	echo "It is in /usr/share/qa/qa_test_slepos/local_config.sh or its symlink /root/qa_slepos-local_config.sh."
	exit 2
fi

source "$CONF_PATH"/role_and_version_detection.sh

# create image server control file
if [ "$pos_version" != 9 ]; then
	image_count="`ls "$CONF_PATH/image-"*.sh | wc -l`"
	if [ "$on_image" ]; then
		{
		cat << EOF
timer 7200
fg 1 copy_repositories $SLEPOS_LIB copy_repositories
wait

EOF

		for i in "$CONF_PATH"/image-*.sh; do
			IMAGE_NAME="${i##$CONF_PATH/image-}"
			IMAGE_NAME="${IMAGE_NAME%%.sh}"
			if [ "$IMAGE_NAME" = desktop -a "$pos_version" = 11 ]; then
				continue
			fi
			# create image, copy to the right place and create scPosimage objects in LDAP
			cat << EOB
timer 1200
fg 1 create_image_$IMAGE_NAME $SLEPOS_LIB create_image $IMAGE_NAME
wait

timer 300
fg 1 put_image_to_admin_server_$IMAGE_NAME $SLEPOS_LIB put_image_to_admin_server -f $IMAGE_NAME
wait

timer 300
fg 1 add_image_to_ldap_$IMAGE_NAME $SLEPOS_LIB add_image_to_ldap $IMAGE_NAME
wait
EOB
		done
		} > $TCF_DIR/qa_slepos-image.tcf
	elif [ "$image_server" ]; then
		{
		cat << EOF
timer 7200
fg 1 copy_repositories ssh root@$image "$SLEPOS_LIB copy_repositories"
wait

EOF

		for i in "$CONF_PATH"/image-*.sh; do
			IMAGE_NAME="${i##$CONF_PATH/image-}"
			IMAGE_NAME="${IMAGE_NAME%%.sh}"
			if [ "$IMAGE_NAME" = desktop -a "$pos_version" = 11 ]; then
				continue
			fi
			# create image, copy to the right place and create scPosimage objects in LDAP
			cat << EOB
timer 1200
fg 1 create_image_$IMAGE_NAME ssh root@$image_server "$SLEPOS_LIB create_image $IMAGE_NAME"
wait

timer 300
fg 1 put_image_to_admin_server_$IMAGE_NAME ssh root@$image_server "$SLEPOS_LIB put_image_to_admin_server -f $IMAGE_NAME"
wait

timer 300
fg 1 add_image_to_ldap_$IMAGE_NAME ssh root@$image_server "$SLEPOS_LIB add_image_to_ldap $IMAGE_NAME"
wait
EOB
		done
		} > $TCF_DIR/qa_slepos-image.tcf
	else
		echo "This is not image server and \`image_server' variable is not defined!"
		exit 1
	fi
fi

for i in $branch_server_list; do
	[ -d "$TCF_DIR/$i" ] || mkdir -p "$TCF_DIR/$i"
	cat << EOB > $TCF_DIR/$i/qa_slepos-branch.tcf
timer 300
fg 1 transfer_config $SLEPOS_LIB transfer_config $i
wait

timer 300
fg 1 run_posInitBranchserver ssh root@$i "$SLEPOS_LIB run_posInitBranchserver"
wait

timer $((image_count * 600))
fg 1 possyncimages.pl ssh root@$i "$SLEPOS_LIB possyncimages.pl"
wait

timer 300
fg 1 rcposleases2ldap_start ssh root@$i "$SLEPOS_LIB rcposleases2ldap start"
wait
EOB
done

if [ "$NO_ADMIN" != yes ]; then
	$CTCS2_DIR/tools/run $TCF_DIR/qa_slepos-admin.tcf
fi

# only kiwi based image building is implemented, that means only SLEPOS 10 and 11 are supported
if [ "$pos_version" != 9 -a "$NO_IMAGE" != yes ]; then
	$CTCS2_DIR/tools/run $TCF_DIR/qa_slepos-image.tcf
fi

if [ "$NO_BRANCH" != yes ]; then
	for i in $branch_server_list; do
		ssh -t root@$i "$SLEPOS_LIB branch_net_up; $SLEPOS_LIB firewall_ports branch_server_ports"
		screen -m -d -S "$i" $CTCS2_DIR/tools/run $TCF_DIR/$i/qa_slepos-branch.tcf
		# I need to be sure that the time differs for each branch server
		sleep 1
	done
fi


