." Manpage for qa_test_aim7.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_aim7 man page"
.SH NAME
qa_test_aim7
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
The AIM Multiuser Benchmark - Suite VII tests and measures theperformance of Open System multiuser computers. Multiuser computerenvironments typically have the following general characteristics incommon:
.br
- A large number of tasks are run concurrently
.br
- Disk storage increases dramatically as the number of users increase.
.br
- Complex numerically intense applications are performed infrequently.
.br
- An important amount of time is spent sorting and searching through large amounts of data.
.br
- After data is used it is placed back on disk because it is a shared resource.
.br
- A large amount of time is spent in common runtime libraries.
.br
Multiuser systems are commonly used to support the following types of user environments:
.br
- Multiuser/shared system environment performing office automation, word processing, spreadsheet, email, database, payroll, and data processing.
.br
- Compute server environment that uses an extremely large quantity of data, performs large quantities of floating point calculations, and large amounts of Interprocess Communications (IPC) for graphics.
.br
- Large database environment with a lot of disk I/O, data in memory, and IPC via shared memory.
.br
- File server environment with a heavy concentration of integer compute file system operations.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
License: GPL v2 or later. Spec file license: GPL. Copyright: Caldera.
.SH UPSTREAM
http://xmacro.sourceforge.net/
.SH AUTHOR
None.
.SH MAINTAINER
Vilem Marsik <VMarsik@novell.com>
