#!/bin/sh

#fix bug Bug 706593 define the max connection of mysqld 
sed -i '/^max_connections/d' /etc/my.cnf
echo "max_connections = 1000000" >>/etc/my.cnf

if [ -d /abuild ]
then
    TESTDIR="/abuild/qa_test_sysbench"
else
    TESTDIR="/tmp/qa_test_sysbench"
fi

BASEDIR="/usr/lib/ctcs2/"

mkdir -p $TESTDIR
cd $TESTDIR
$BASEDIR/tools/run $BASEDIR/tcf/sysbench.tcf
rm $TESTDIR/test_file*
