." Manpage for qa_test_hazard.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_hazard man page"
.SH NAME
qa_test_hazard
.SH SYNOPSIS
hazard_run.sh [options] ip [ip2] [ip3]
.SH TYPE
Stress test suite
.SH DESCRIPTION
Hazard is a test tool that provides automated storage device reliability testing which focuses on high availability (HA) issues.
.br
It's a distributable test tools which works in Controller/Clients mode.
.SH README
None. 
.SH OPTIONS
-t specify the running time.
.br
-c [1-15] specify the configuration.
.SH WHAT IT DOES
setup the environment for clients and start the IO test automatically.
.br
after the time which was specified before running, Controller collect the log from and clean the session.
.SH COMMON PROBLEMS
License issue, passwd issue.
.SH WARNINGS
Implement this test suite by hamsta.
.br
Keep a stable network
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Proprietary, no patches. Provided by HP under NDA, not to be redistributed.
.SH LICENSE
License: HP proprietary. Spec file license: GPL v2 or later. HP licensed to us for internal use on HP hardware.
.SH UPSTREAM
http://qa.suse.de/
.SH AUTHOR
Jerry Tang <jtang@novell.com>
.SH MAINTAINER
Jerry Tang <jtang@novell.com>
