set ip [ lindex $argv 0 ]
set passwd [ lindex $argv 1 ]
if { $ip == "" } { exit 2 }
if { $passwd == "" } { exit 2 }

spawn -nottyinit ssh-copy-id -i /root/.ssh/id_rsa.pub root@$ip

set timeout 5
		
expect "Are you sure you want to continue connecting (yes/no)?"
send "yes\012"
expect {
	 -re "Now try logging into the machine" { exit 0 }
	"Password:" { send "$passwd\012" }
}
expect -re "Now try logging into the machine"
exit 0 
expect timeout
exit 2;close 

