." Manpage for qa_test_sched_stress.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_sched_stress man page"
.SH NAME
qa_test_sched_stress
.SH SYNOPSIS
/usr/share/qa/tools/test_sched_stress-run
.SH TYPE
Stress test for schedule.
.SH DESCRIPTION
One of the validation test cases, which focuses on scheduler stress test.
.SH README
None.
.SH OPTIONS
None
.SH WHAT IT DOES
Implement /opt/lpt/testcases/bin/sched_stress.sh.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Yi Xu <yxu@novell.com>
.SH MAINTAINER
csxia@novell.com
