." Manpage for qa_test_suse-cert.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_suse-cert man page"
.SH NAME
qa_test_suse-cert
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
All tests and tools for SLES9/SLES10/SLED10 certifications are included in this package. Those tests are meant to be run from the System Test Kit via TestConsole.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, no patches. Old package, replaced by tck-sut/tck-* (cf with Craig Salmond).
.SH LICENSE
License: n/a. Spec file license: GPL v2 or later.
.SH UPSTREAM
None.
.SH AUTHOR
Klaus G. Wagner <kgw@suse.de>, Thomas Siedentopf <tsieden@suse.de>, Olli Ries <ories@suse.de>, Gerald Bringhurst <gbringhurst@suse.de>
.SH MAINTAINER
Arthur Guo <aguo@novell.com>
