#!/bin/bash
# ****************************************************************************
# Copyright © 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#

#this script generate tcf dynamically

templateroot=/root
tcf_file=/usr/share/qa/qa_test_kiwi/tcf/qa_kiwi.tcf
touch /tmp/kiwi_dg_$$
echo "" > $tcf_file
grep -v '#' /usr/share/qa/qa_test_kiwi/qa_kiwi_dict.conf > /tmp/kiwi_dg_$$

awk '{a=split($3,repo,/,/);s=gensub(/.*\//,"",1,$2);ii=0;for(i in repo){ii++;gsub(/[)(]/," ",repo[i]);print $2,s"/"$1"/"ii,repo[i]} }' /tmp/kiwi_dg_$$|while read  templatel destdir repourl repotype
do
sh_file_name=`echo $destdir|sed 's#/#-#g'` 
#echo $sh_file_name
mkdir -p $templateroot/$destdir/
echo "kiwi --build $templatel --destdir $templateroot/$destdir/ --set-repo $repourl --set-repotype $repotype" > /usr/share/qa/qa_test_kiwi/${sh_file_name}.sh
chmod a+x /usr/share/qa/qa_test_kiwi/${sh_file_name}.sh
echo 
echo "timer 3h" >> $tcf_file
echo "fg 1 ${sh_file_name} /usr/share/qa/qa_test_kiwi/${sh_file_name}.sh" >>$tcf_file
echo "wait" >> $tcf_file
echo "" >> $tcf_file

done

rm /tmp/kiwi_dg_$$

/usr/lib/ctcs2/tools/run /usr/share/qa/qa_test_kiwi/tcf/qa_kiwi.tcf

