." Manpage for qa_test_iperf.
." Contact Yi Xu <yxu@suse.com> to correct errors or typos.
.TH man 8 "05 Dec 2012" "1.0" "qa_test_iperf man page"
.SH NAME
qa_test_iperf
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Iperf was developed by NLANR/DAST as a modern alternative for measuring maximum TCP and UDP bandwidth performance. Iperf allows the tuning of various parameters and UDP characteristics. Iperf reports bandwidth, delay jitter, datagram loss.
.br
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Measure maximum TCP and UDP bandwidth performance.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://iperf.sourceforge.net/
.SH AUTHOR
NLANR/DAST
.SH MAINTAINER
Yi Xu <yxu@suse.com>
