#!/bin/bash
PATH='/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin'

ctcsdir="/usr/lib/ctcs2"
basedir="/usr/share/qa/tcf"
TCF_FILE="$basedir/netperf-peer-fiber6.tcf"
cat <<EOF >${TCF_FILE}
timer 25m
fg 1 netperf-fiber-tcp6  /usr/lib/ctcs2/config/netperf/netperf-client -6 -T -a ::ffff:192.168.10.54 -m 64 -i eth5 -p ::ffff:192.168.10.53
wait

timer 25m
fg 1 netperf-fiber-udp6 /usr/lib/ctcs2/config/netperf/netperf-client -6 -U -a ::ffff:192.168.10.54 -m 64 -i eth5 -p ::ffff:192.168.10.53
wait
EOF

$ctcsdir/tools/run ${TCF_FILE}

