#!/bin/bash

IP=127.0.0.1
BRD=127.0.0.255
MASK=24
PEER_IP=127.0.0.1
INTERFACE=eth0

function usage
{
    echo 'usage'
    exit 2
}

while test $# -gt 0; do
    opt=$1
    echo $opt | grep '^-' > /dev/null
    if test $? -ne 0; then
        break
    fi
    case $opt in
        '-a') if test $# -lt 2;then usage; else shift; fi
            IP=$1;;
        '-b') if test $# -lt 2;then usage; else shift; fi
            BRD=$1;;
        '-m') if test $# -lt 2;then usage; else shift; fi
            MASK=$1;;
        '-i') if test $# -lt 2;then usage; else shift; fi
            INTERFACE=$1;;
        '-p') if test $# -lt 2;then usage; else shift; fi
            PEER_IP=$1;;
    esac
    shift
done

echo "IP $IP"
echo "INTERFACE $INTERFACE"
echo "PEER_IP $PEER_IP"
echo "MASK $MASK"
echo "BRD $BRD"

if test ! -d /sys/class/net/${INTERFACE};then
    echo "E interface ${INTERFACE} dose not exist!!!"
    exit 3
fi

if ip addr show dev ${INTERFACE} | grep ${IP} > /dev/null; then
    echo "I ${INTERFACE} already have ${IP}"
else
    ip addr add ${IP}/${MASK} brd ${BRD} dev ${INTERFACE}
    if $? -ne $0; then
        echo "E failed to add the ip"
        exit 3
    fi
fi

# make sure link is up
ip link set ${INTERFACE} up

for pid in $(pidof netserver);do
    kill -9 $pid
done
netserver
exit $?
