#!/bin/bash 
PATH='/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin'

ctcsdir="/usr/lib/ctcs2"
basedir="/usr/share/qa/tcf"

# Source the variable settings
source /usr/lib/ctcs2/config/netperf/qa_test_netperf-config

choose_test_dev()
{
	for dev in `ls /sys/class/net/`
	do
        	default_dev=`ip route | grep default | awk '{print $5}'`
        	if [ $dev == $default_dev -o $dev == lo ];then
                	continue
        	fi
        	ethtool $dev | grep "Link detected: yes" >> /dev/null
        	test_dev=$dev
done

}

choose_test_dev

ipinfo=`ifconfig |sed -n '/inet addr:/{s/ [BM].*//;s/.*://;p}'`


if [ -z "$ipinfo" ];then
	echo "Can't get ip address"
	exit 1
fi

#find out the server
for i in $ipinfo
do

	flag=`echo $i|sed 's/\.[0-9]\+\.[0-9]\+$//'`
	if [ "$flag" == "$DE_1" ];then
		ip=$DE_netperf_server_1
		break
	elif [ "$flag" == "$DE_2" ];then
		ip=$DE_netperf_server_2
		break
	elif [ "$flag" == "$CZ" ];then
		ip=$CZ_netperf_server
		break
	elif [ "$flag" == "$CN" ];then
		ip=$CN_netperf_server
		ip6=$CN_netperf_server_v6
		ip address add 192.168.1.100/24 dev $test_dev
		ip address add 2001::100/64 dev $test_dev
                break
	else
		echo No server matched from $i
	fi
		
done

if [ -z "$ip" ];then
	echo "Server was not definded"
	exit 1
fi

port=12865

#check the server's port
telnet -c -ex $ip $port  <<aquit
x
quit
aquit
if [ $? -gt 0  ];then
	echo "The server[ $ip ] does not start the service"
	exit 1
fi
#modify the tcf file
sed -i "s/IP/$ip/g" $basedir/netperf.tcf

$ctcsdir/tools/run $basedir/netperf.tcf

if [ $ip6 ];then
	sed -i "s/IP/$ip6/g" $basedir/netperf6.tcf
	$ctcsdir/tools/run $basedir/netperf6.tcf
fi

