." Manpage for qa_test_memeat.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_memeat man page"
.SH NAME
qa_test_qa_test_memeat
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Contains an easy program that eats up nearly all available (low) memory of the system and does read and write operations on it.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, 2 patches.
.SH LICENSE
No license agreement found in package
.SH UPSTREAM
None.
.SH AUTHOR
Andi Kleen <ak@suse.de>
.SH MAINTAINER
Erik Hamera <erik.hamera@novell.com>
