#!/usr/bin/expect -f
# ****************************************************************************
# Copyright © 2011 Unpublished Work of SUSE, Inc. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE, INC.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************

source /usr/share/qa/qa_test_cracklib/cracklib_tests.conf

set timeout	$default_timeout 
set FAILED 0

log_user 1

catch { exec useradd -m $cracklib_user -d /tmp/testhome}

system sync

spawn passwd $cracklib_user

expect {
	$cracklib_expectnew {
		sleep 1
		send $cracklib_pass
	}
	timeout {
        puts "FAILED: cracklib - similar passwd - did not get cracklib_expectnew"
        set FAILED 1
	}
}

expect {
	$cracklib_expectretype {
		sleep 1
		send $cracklib_pass
		sleep 1 
	}
	timeout {
		puts "FAILED: cracklib - similar passwd - did not get cracklib_expectretype"	
        set FAILED 1
	}
}
close

system sync

spawn $default_shell
send "su $cracklib_user -c passwd\r"
expect {
	$cracklib_expectcurrent {
		sleep 1
		send $cracklib_pass
	}
	timeout {
        puts "FAILED: cracklib - similar passwd - did not get cracklib_expectcurrent"
        set FAILED 1
	}
}

expect {
	$cracklib_expectnew {
		sleep 1
		send $cracklib_passsimilar
	}
	timeout {
        puts "FAILED: cracklib - similar passwd - did not get cracklib_expectnew"
        set FAILED 1
	}
}

expect {
	$cracklib_expectedsimilar {
		puts "PASSED: cracklib - similar passwd"
		close
		catch { exec userdel -r $cracklib_user }
	}

	timeout {
		puts "FAILED: cracklib - similar passwd  - did not get cracklib_expectedsimilar"
		close
		catch { exec userdel $cracklib_user }
        set FAILED 1
	}
}

system sync

exit $FAILED


