." Manpage for qa_test_iogen.
." Contact Yi Xu <yxu@suse.com> to correct errors or typos.
.TH man 8 "24 Jun 2013" "3.1" "qa_test_iogen man page"
.SH NAME
qa_test_iogen
.SH SYNOPSIS
None.
.SH TYPE
I/O generator
.SH DESCRIPTION
iogen is a lightweight tool that generates heavily fragmented I/O.
It accomplishes this by forking a number of children that run I/O to a filesystem.
.br
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
forking a number of children that run I/O to a filesystem
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
BSD
.SH UPSTREAM
http://www.peereboom.us/iogen/
.SH AUTHOR
NLANR/DAST
.SH MAINTAINER
Yi Xu <yxu@suse.com>
