." Manpage for qa_test_evolution.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_evolution man page"
.SH NAME
qa_test_evolution
.SH SYNOPSIS
/usr/share/qa/qa_test_evolution/test_evolution-run or /usr/share/qa/qa_test_evolution/qa_test_evolution/evolution*.py
.SH TYPE
UI function test
.SH DESCRIPTION
Internal test suite for testing the Evolution collaboration software based on QA team's test plan #3130.
.br
Scripts are written in Python.
.SH README
qa_test_evolution tests the following: Evolution startup, account configuration, sending mail, and receiving mail.
.SH OPTIONS
None.
.SH WHAT IT DOES
/usr/share/qa/qa_test_evolution/qa_test_evolution/evolution*.py will be run.
.br
A series of UI tests of Evolution will be implemented automatically.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. No licence provided in the sources. Internal development. Meant to be GPL.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Calen Chen <cachen@novell.com>
.SH MAINTAINER
Calen Chen <cachen@novell.com>
