#!/bin/bash
# ****************************************************************************
# Copyright (c) 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#
# Run setupUIAutomation test script to restore X window if running display is not equal to 1
displays=(`who |awk {'print $2'} |grep :[0-9]`)

if [ "${#displays[*]}" -eq 0 ] || [ "${#displays[*]}" -gt 1 ]; then
	/usr/share/qa/tools/setupUIAutomationtest
	sleep 60
fi

who_info=(`who |awk {'print $1,$2'} |grep :[0-9]`)
username=${who_info[0]}
display=${who_info[1]}

echo "INFO: User $username run test on display $display.0"

# Run test
comments="
export LANG=C
export DISPLAY=$display.0
xhost +
gnome-screensaver-command -d
killall -9 -q /usr/lib/at-spi/at-spi-registryd evolution
[ `ps aux | grep at-spi-registry | wc -l` -gt 1 ] || /usr/lib/at-spi/at-spi-registryd&
/usr/lib/ctcs2/tools/run /usr/share/qa/tcf/qa_evolution.tcf"

# Kill the exist evolution first
ps -ef |grep evolution |grep -v grep |grep -v "/bin/bash" |awk '{print $2}' |xargs --no-run-if-empty kill -9

# Run test
if [ "$username" != "root" ]; then
	su - $username 2>/dev/null -c "$comments"
	cp -r `getent passwd $username | cut -d: -f 6`/var-log-qa/* /var/log/qa
	su - $username 2>/dev/null -c "cd; rm -fr var-log-qa"
else
	sh -c "$comments"
fi

