." Manpage for qa_test_nfs.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_nfs man page"
.SH NAME
qa_test_nfs
.SH SYNOPSIS
/usr/share/qa/tools/test_nfs-run or /usr/share/qa/tools/test_nfs-v4-run
.SH TYPE
Function test suite
.SH DESCRIPTION
Basic NFS tests for nfsv3 and nfsv4.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Test suite will start nfs service and verify service with: "start & stop", "mount & umount", "read & write", "readonly" and "usermapping".
.SH COMMON PROBLEMS
None.
.SH WARNINGS
Implement this test suite using hamsta.
.br
Don't use nfs service on SUT during test.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, 1 patch. Written internally. Sources already posted outside.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
None.
.SH AUTHOR
gnu.org <gnu.org>
.SH MAINTAINER
Jerry Tang <jtang@novell.com>
