." Manpage for qa_test_f-spot.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_f-spot man page"
.SH NAME
qa_test_f-spot
.SH SYNOPSIS
/usr/share/qa/tools/qa_test_f-spot-run
.SH TYPE
UI function test
.SH DESCRIPTION
Test Cases for f-spot, now only contains test cases for import images.
.br
Scripts are written in Python.
.SH README
None. 
.SH OPTIONS
None
.SH WHAT IT DOES
A series of UI tests of f-spot will be implemented automatically.
.SH COMMON PROBLEMS
None
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. No licence provided in the sources. Internal development. Meant to be GPL.
.SH LICENSE
License: n/a. Spec file license: GPL.
.SH UPSTREAM
http://w3d.suse.de/Dev/QA/
.SH AUTHOR
Chengshun Xia <csxia@novell.com>
.SH MAINTAINER
csxia@novell.com
