." Manpage for qa_test_libmicro.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_libmicro man page"
.SH NAME
qa_test_libmicro
.SH SYNOPSIS
/usr/lib/ctcs2/tools/test_qa_test_libmicro-run or /usr/lib/ctcs2/tools/test_qa_test_libmicro-bench-run
.SH TYPE
performance test
.SH DESCRIPTION
LibMicro is intended to measure the performance of various system and library calls.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Two tcf files can be found in this suite. "test_qa_test_libmicro-run" keeps running this test for 1 hour, while "qa_test_libmicro-bench" will run test only once.
.SH COMMON PROBLEMS
Performance will slow down SUT.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, 3 patches from us.
.SH LICENSE
License: CDDL. Spec file license: CDDL.
.SH UPSTREAM
http://www.opensolaris.org/os/project/qa_test_libmicro/
.SH AUTHOR
Various people from OpenSolaris community <pkirsch@suse.de>.
.SH MAINTAINER
Arthur Guo <aguo@novell.com>
