#!/bin/bash

# Source the variable settings
source /usr/share/qa/qa_test_hacluster/qa_test_hacluter-config

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf

cd $CTCS2_DIR

#modify the tcf file to give arguments
sed -i "/^fg.*$/s/-b.*-s/-b $bindnetaddr -m $mcastaddr -i $iscsi_sbd_host -s/g" $TCF_DIR/qa_hacluster.tcf

tools/run $TCF_DIR/qa_hacluster.tcf
