." Manpage for qa_test_autotest.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_test_autotest man page"
.SH NAME
qa_test_autotest
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
Autotest with the packed tests/suites is used for kernel testing. This harness especially is used for testing the mainline kernel.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches. Only redistributed/packaged to fullfil dependencies.
.SH LICENSE
License: MIT; Apache 2.0. Spec file license: GPL v2.
.SH UPSTREAM
http://test.kernel.org/qa_test_autotest
.SH AUTHOR
Various people from test.kernel.org
.SH MAINTAINER
csxia@novell.com
