#!/bin/bash
/usr/share/hamsta/testscript/autotest aio_dio_bugs aiostress bash_shared_mapping bonnie cyclictest dbench dbt2 disktest fio interbench iozone isic kernbench kernelbuild libhugetlbfs linus_stress lmbench pi_tests pktgen rmaptest scrashme signaltest sleeptest sparse spew stress tbench tiobench tsc unixbench xmtest sysbench barriertest btreplay dacapo cpu_hotplug
