." Manpage for qa_test_gnome.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_test_gnome man page"
.SH NAME
qa_test_gnome
.SH SYNOPSIS
/usr/share/qa/qa_test_gnome/test_gnome-run
, /usr/share/qa/qa_test_gnome/qa_test_gnome/gnome*.py
.SH TYPE
UI function test
.SH DESCRIPTION
gnome is a desktop environment / graphical user interface that runs on top of a computer operating system.
.br
A series of tests for gnome based on QA team's test plan #2781.
.br
Scripts are written by Python.
.SH README
None.
.SH OPTIONS
None
.SH WHAT IT DOES
/usr/share/qa/qa_test_gnome/qa_test_gnome/gnome*.py will be run.
.br
A series of UI tests of gnome will be implemented automatically.
.SH COMMON PROBLEMS
None
.SH WARNINGS
None
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
None.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Calen Chen <cachen@novell.com>
.SH MAINTAINER
Calen Chen <cachen@novell.com>
