#!/bin/bash
username=`who |grep ":[0-9] " |awk {'print $1'}`
DISPLAY=`who |grep ":[0-9] " |awk {'print $2'}`.0

# Add non-root user to sudoers to use sudo comment without root password in test
if [[ "$username" != "root" && `grep -c "$username ALL=(ALL)" /etc/sudoers` -eq 0 ]];then
	echo "# $username withouth password" >>/etc/sudoers
	echo "$username ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
fi

comments="
export LANG=C
export DISPLAY=$DISPLAY
xhost +
killall /usr/lib/at-spi/at-spi-registryd
[ `ps aux | grep at-spi-registry | wc -l` -gt 1 ] || /usr/lib/at-spi/at-spi-registryd&
/usr/lib/ctcs2/tools/run /usr/share/qa/tcf/qa_gnome.tcf"

if [ "$username" != "$USER" ]; then
	su - $username -c "$comments"
	cp -r `getent passwd $username | cut -d: -f 6`/var-log-qa/* /var/log/qa
	su - $username -c "cd; rm -fr var-log-qa"
else
	sh -c "$comments"
fi
