#!/bin/bash


svn export https://forgesvn1.novell.com/svn/apparmor/trunk/tests tests | sed -n 's/Exported revision \([0-9]*\).*$/\1/p' > /tmp/qa_apparmor_revision
REVISION=`cat /tmp/qa_apparmor_revision`
rm -rf /tmp/qa_apparmor_revision
svn export https://forgesvn1.novell.com/svn/apparmor/trunk/parser/tst parser > /dev/null
mv parser tests
tar -cjf tests-$REVISION.tar.bz2 tests
rm -rf tests
