#!/bin/bash

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf

$CTCS2_DIR/tools/run $TCF_DIR/qa_apparmor.tcf
#restart the default configuration so we are sure failed apparmor testcases
#didn't break the whole system
/sbin/rcapparmor restart
