#!/bin/bash

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf

shopt -s sourcepath

#restart appamor to be sure its running
/sbin/rcapparmor restart

#start apache2 for testing apparmor profile

systemctl stop apache2  > /dev/null 2>&1

systemctl start apache2  > /dev/null 2>&1

RC=$?
if [ $RC -eq 0 ]
    then
    $CTCS2_DIR/tools/run $TCF_DIR/qa_apparmor_profiles.tcf
fi

