#!/bin/bash

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf

shopt -s sourcepath

#restart appamor to be sure its running
/sbin/rcapparmor restart
$CTCS2_DIR/tools/run $TCF_DIR/qa_apparmor_profiles.tcf
