#! /bin/sh
# Copyright (c) 1995-1998 SuSE GmbH Nuernberg, Germany.
#
# Author: adrian@suse.de, template by ro@suse.de
#
# /etc/init.d/fam
#   and its symbolic  link
# /usr/sbin/fam
#
### BEGIN INIT INFO
# Provides:          fam
# Required-Start:    $remote_fs xntpd $named $syslog
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:
# Description:       file access monitoring
### END INIT INFO

. /etc/rc.status
. /etc/rc.config


test -x /usr/sbin/fam || exit 0

rc_reset
case "$1" in
    start)
	echo -n "Starting File Access Monitoring Daemon"

	startproc /usr/sbin/fam -T 0
	rc_status -v
	;;
    stop)
	echo -n "Shutting down File Access Monitoring Daemon"
	killproc -TERM /usr/sbin/fam
	rc_status -v
	;;
    restart)
	## If first returns OK call the second, if first or
	## second command fails, set echo return value.
	$0 stop; sleep 1  &&  $0 start
	rc_status
	;;
    reload)
	$0 stop  &&  $0 start
	rc_status
	;;
    status)
	echo -n "Checking for File Access Monitoring Daemon: "
	checkproc /usr/sbin/fam
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
	;;
esac
rc_exit
