#! /bin/sh
# Copyright (c) 1995-2001 SuSE GmbH Nuernberg, Germany.
#
# Author: adrian@suse.de
#
# /etc/init.d/ksysguardd
#   and its symbolic  link
# /usr/sbin/rcksysguardd
#
### BEGIN INIT INFO
# Provides:          ksysguardd
# Required-Start:    xntpd $named $syslog
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:
# Description:       remote monitor daemon for ksysguard
### END INIT INFO

. /etc/rc.status
. /etc/rc.config


test -x /usr/bin/ksysguardd    || exit 0

rc_reset
case "$1" in
    start)
	echo -n "Starting remote monitor daemon for ksysguard "

#	startproc /usr/bin/ksysguardd3 -d >/dev/null
	rc_status -v
	;;
    stop)
        if [ -e /var/run/ksysguardd.pid ]; then
	   echo -n "Shutting down remote monitor daemon for ksysguard "
#	   killproc -p /var/run/ksysguardd.pid -TERM /usr/bin/ksysguardd3
	   rc_status -v
        fi
	;;
    restart)
	## If first returns OK call the second, if first or
	## second command fails, set echo return value.
	$0 stop; sleep 1  &&  $0 start
	rc_status
	;;
    reload)
	$0 stop  &&  $0 start
	rc_status
	;;
    status)
	echo -n "Checking for remote monitor daemon for ksysguard "

        checkproc /usr/bin/ksysguardd
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
	;;
esac
rc_exit
