#! /bin/sh
# Copyright (c) 1995-2001 SuSE GmbH Nuernberg, Germany.
#
# Author: adrian@suse.de
#
# /etc/init.d/lisa
#   and its symbolic  link
# /usr/sbin/rclisa
#
### BEGIN INIT INFO
# Provides:          lisa
# Required-Start:    xntpd $named $syslog
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:
# Description:       lan browser daemon for KDE
### END INIT INFO

test -r /etc/rc.config && \
      . /etc/rc.config
test -r /etc/sysconfig/lisa && \
      . /etc/sysconfig/lisa


test "$USE_LISA" = "local" -o "$USE_LISA" = "server" || exit 0
test -x /usr/sbin/lisa                               || exit 0

rc_reset
case "$1" in
    start)
	echo -n "Starting lan browser daemon for KDE"

	startproc /usr/sbin/lisa -c /etc/lisarc >/dev/null
	rc_status -v
	;;
    stop)
	echo -n "Shutting down lan browser daemon for KDE"
	killproc -TERM /usr/sbin/lisa
	rc_status -v
	;;
    restart)
	## If first returns OK call the second, if first or
	## second command fails, set echo return value.
	$0 stop; sleep 1  &&  $0 start
	rc_status
	;;
    reload)
	$0 stop  &&  $0 start
	rc_status
	;;
    status)
	echo -n "Checking for lan browser daemon for KDE: "

	checkproc /usr/sbin/lisa
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
	;;
esac
rc_exit
