#! /bin/sh
# Copyright (c) 1995-2001 SuSE GmbH Nuernberg, Germany
#
# init.d/named
#
### BEGIN INIT INFO
# Provides:       named
# Required-Start: $network $remote_fs $syslog
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:
# Description:    Starts internet domain name server (DNS)
### END INIT INFO

. /etc/rc.config
NAMED_BIN=/usr/sbin/named
NAMED_PID=/var/run/named.pid
NAMED_CONF=/etc/named.conf

if [ ! -x $NAMED_BIN ] ; then
	echo -n "Name server not installed ! "
	exit 5
fi

. /etc/rc.status
rc_reset

case "$1" in
    start)
	echo -n "Starting name server BIND8 "
	checkproc $NAMED_BIN
	if [ $? -eq 0 ] ; then
	   echo -n "- Warning: named already running ! "
	else
	   [ -e $NAMED_PID ] && echo -n "- Warning: $NAMED_PID exists ! "
	fi
	startproc $NAMED_BIN -u named -g named
	rc_status -v
	;;
    stop)
	echo -n "Shutting down name server BIND8 "
	checkproc $NAMED_BIN || echo -n "- Warning: named not running ! "
	killproc -TERM $NAMED_BIN
	rc_status -v
	;;
    try-restart)
	$0 stop  &&  $0 start
	rc_status
	;;
    restart)
	$0 stop
	$0 start
	rc_status
	;;
    force-reload)
	$0 reload
	rc_status
	;;
    reload)
	echo -n "Reloading name server BIND8 "
	checkproc $NAMED_BIN || echo -n "- Warning: named not running ! "
	killproc -HUP $NAMED_BIN
	# [ -e $NAMED_PID ] && touch -c -m $NAMED_PID
	rc_status -v
	;;
    status)
	echo -n "Checking for nameserver BIND8 "
	checkproc $NAMED_BIN
	rc_status -v
	;;
    probe)
	test $NAMED_CONF -nt $NAMED_PID && echo reload
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
	exit 1
	;;
esac
rc_exit

