#! /bin/sh
# Copyright (c) 2001 SuSE GmbH Nuernberg, Germany.
#
# Author: Wolfgang Rosenauer <feedback@suse.de>, 2000, 2001
#
# /etc/init.d/radiusd
#
#   and symbolic its link
#
# /usr/sbin/rcradiusd
#
### BEGIN INIT INFO
# Provides:       radiusd
# Required-Start: $network $syslog $remote_fs
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Description:    RADIUS-Server
### END INIT INFO


. /etc/rc.status

test -x /usr/sbin/radiusd || exit 5

rc_reset
case "$1" in
    start)
	echo -n "Starting service radiusd"

	test -f /etc/raddb/clients || rc_failed 6
	rc_check
	if [ $? -eq 0 ]
	then
	  if [ -x /usr/sbin/radwatch ] 
	  then
	    /usr/sbin/radwatch 
	  else
	    startproc /usr/sbin/radiusd 
	  fi
	fi

	rc_status -v	
	;;
    stop)
	echo -n "Shutting down service radiusd"

	if [ -e /var/run/radwatch.pid ]
	then
	  kill `cat /var/run/radwatch.pid` 
	fi
	killproc -TERM /usr/sbin/radiusd 

	rc_status -v	
	;;
    try-restart)
	## If first returns OK call the second, if first or
	## second command fails, set echo return value.
	$0 status >/dev/null &&  $0 restart
	rc_status
	;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
	$0 stop
	$0 start
	rc_status
	;;
    force-reload)
        ## Signal the daemon to reload its config. Most daemons
        ## do this on signal 1 (SIGHUP).
        ## If it does not support it, restart.

	echo -n "Reload service radiusd"
        /usr/sbin/radiusd -C > /dev/null 2>&1
        retval=$?
        if [ $retval -eq 0 ]
        then
          killproc -HUP /usr/sbin/radiusd
        else
          echo -ne "\nerror in configuration!\nnot reloaded!"
          rc_failed 6
        fi
        rc_status -v
	;;
    reload)
        ## Like force-reload, but if daemon does not support
        ## signalling, do nothing (!)

	echo -n "Reload service radiusd"
	/usr/sbin/radiusd -C > /dev/null 2>&1
	retval=$?
	if [ $retval -eq 0 ]
	then
	  killproc -HUP /usr/sbin/radiusd 
	else
	  echo -ne "\nerror in configuration!\nnot reloaded!"
	  rc_failed 6
        fi
	rc_status -v
	;;
    status)
	echo -n "Checking for service radiusd: "

	checkproc /usr/sbin/radiusd

	rc_status -v	
	;;
    probe)
        ## Optional: Probe for the necessity of a reload,
        ## give out the argument which is required for a reload.
        
        test /etc/raddb/users -nt /var/run/radiusd.pid && echo RELOAD || echo No changes in /etc/raddb/users
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
	exit 1
	;;
esac
rc_exit
