#! /bin/sh
# Copyright (c) 1996-2001 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Remo Behn <ray@suse.de>, 2000
#
# /etc/init.d/snmpd
#
### BEGIN INIT INFO
# Provides:            ucdsnmp snmp
# Required-Start:      $network
# Required-Stop:
# Default-Start:       2 3 5
# Default-Stop:        0 1 6
# Description:         start ucd-snmpd
### END INIT INFO

# Source SuSE config
. /etc/rc.config

SNMPD=/usr/sbin/snmpd

test -x $SNMPD || exit 5

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_failed <num>  set local and overall rc status to <num><num>
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
. /etc/rc.status

# First reset status of this service
rc_reset

# Return values acc. to LSB for all commands but status:
# 0 - success
# 1 - generic or unspecified error
# 2 - invalid or excess argument(s)
# 3 - unimplemented feature (e.g. "reload")
# 4 - insufficient privilege
# 5 - program is not installed
# 6 - program is not configured
# 7 - program is not running
# 
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signalling is not supported) are
# considered a success.

case "$1" in
    start)
	echo -n "Starting snmpd:"
	startproc $SNMPD -c /etc/ucdsnmpd.conf -r -A  \ 
			-l /var/log/ucd-snmpd.log -P /var/run/snmpd.pid
	rc_status -v
	;;
    stop)
	echo -n "Shutting down snmpd:"
	killproc -TERM $SNMPD
	rc_status -v
	;;
    try-restart)
	$0 status >/dev/null &&  $0 restart
	rc_status
	;;
    restart)
	$0 stop
	$0 start
	rc_status
	;;
    force-reload)
	echo -n "Reload service snmpd:"
	killproc -HUP $SNMPD
	rc_status -v
	;;
    reload)
	echo -n "Reload service snmpd:"
	killproc -HUP $SNMPD
	rc_status -v
	;;
    status)
	echo -n "Checking for service snmpd:"
	checkproc $SNMPD
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|try-restart|restart|force-reload|reload|status}"
	exit 1
	;;
esac
rc_exit

