#! /bin/sh
#
# /etc/init.d/splash_early
#
# Copyright (c) 2000, 2001 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
#
### BEGIN INIT INFO
# Provides: splash_early
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start: 2 3 5
# Default-Stop: 0 1 4 6
# Description: kills animation after network start
### END INIT INFO

# Source SuSE config
. /etc/rc.config

. /etc/rc.status

# First reset status of this service
rc_reset

case "$1" in
	start)
		rc_splash "bootnetwork stop"
		;;
	stop|status|restart|reload)
		# rc_status -v3
		;;
esac

rc_exit
