#! /bin/sh
# Copyright (c) 1995-2000 SuSE GmbH Nuernberg, Germany.
#
# Author: Jiri Smid <feedback@suse.de>
#
# /etc/init.d/sshd
#
#   and symbolic its link
#
# /usr/sbin/rcsshd
#
### BEGIN INIT INFO
# Provides: sshd
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the sshd daemon
### END INIT INFO

. /etc/rc.status
. /etc/rc.config
. /etc/sysconfig/ssh

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status

# First reset status of this service
rc_reset
case "$1" in
    start)
        if ! test -f /etc/ssh/ssh_host_key ; then
	    echo Generating /etc/ssh/ssh_host_key.
	    ssh-keygen -b 1024 -f /etc/ssh/ssh_host_key -N ''
        fi
        if ! test -f /etc/ssh/ssh_host_dsa_key ; then
	    echo Generating /etc/ssh/ssh_host_dsa_key.
	    
	    ssh-keygen -t dsa -b 1024 -f /etc/ssh/ssh_host_dsa_key -N ''
        fi
        if ! test -f /etc/ssh/ssh_host_rsa_key ; then
	    echo Generating /etc/ssh/ssh_host_rsa_key.
	    
	    ssh-keygen -t rsa -b 1024 -f /etc/ssh/ssh_host_rsa_key -N ''
        fi
	echo -n "Starting SSH daemon"
	## Start daemon with startproc(8). If this fails
	## the echo return value is set appropriate.

	startproc -f /usr/sbin/sshd $SSHD_OPTS

	# Remember status and be verbose
	rc_status -v
	;;
    stop)
	echo -n "Shutting down SSH daemon"
	## Stop daemon with killproc(8) and if this fails
	## set echo the echo return value.

	if [ -x /bin/netstat ]; then
	   netstat -nlp 2>/dev/null | while read prot a b local remote state prog; do
	      if [ "${local##*:}" = "22" ] ; then 
	         if [ -n "$prog" ]; then
	            kill -TERM ${prog%%/*}
	         fi
	      fi
	   done
	else
	   echo " netstat is missing. I cannot determine if there is"
	   echo "any listening sshd configured via /etc/ssh/sshd_config"
	   echo "to be stoped."
	   rc_failed 1
	fi

	# Remember status and be verbose
	rc_status -v
	;;
    try-restart)
        ## Stop the service and if this succeeds (i.e. the 
        ## service was running before), start it again.
        $0 status >/dev/null &&  $0 restart

        # Remember status and be quiet
        rc_status
        ;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
        $0 stop
        $0 start

        # Remember status and be quiet
        rc_status
        ;;
    force-reload|reload)
	## Signal the daemon to reload its config. Most daemons
	## do this on signal 1 (SIGHUP).

	echo -n "Reload service sshd"

	if [ -x /bin/netstat ]; then
	   netstat -nlp 2>/dev/null | (while read prot a b local remote state prog; do
	         if [ "${local##*:}" = "22" ] ; then
	            LISTENING_SSHD=$prog
	         fi
	      done

	      if [ -n "$LISTENING_SSHD" ]; then
	         kill -HUP ${LISTENING_SSHD%%/*}
	      else
	         rc_failed 7
	      fi
	   )
	else
	   echo " netstat is missing. I cannot determine if there is"
	   echo "any listening sshd configured via /etc/ssh/sshd_config"
	   echo "to be reloded."
	   rc_failed 1
	fi

        rc_status -v

        ;;
    status)
	echo -n "Checking for service sshd: "
        ## Check status with checkproc(8), if process is running
        ## checkproc will return with exit status 0.

        # Status has a slightly different for the status command:
        # 0 - service running
        # 1 - service dead, but /var/run/  pid  file exists
        # 2 - service dead, but /var/lock/ lock file exists
        # 3 - service not running

	if [ -x /bin/netstat ]; then
	   netstat -nlp 2>/dev/null | ( while read prot a b local remote state prog; do
	         if [ "${local##*:}" = "22" ] ; then
	            LISTENING_SSHD=$prog
	         fi
	      done

	      if [ -n "$LISTENING_SSHD" ]; then
	         rc_failed 0
	      else
	         rc_failed 3
	      fi
	   )
	else
	   echo " netstat is missing. I cannot determine if there is"
	   echo "any listening sshd configured via /etc/ssh/sshd_config."
	   rc_failed 1
	fi

	rc_status -v
	;;
    probe)
	## Optional: Probe for the necessity of a reload,
	## give out the argument which is required for a reload.

        test /etc/ssh/sshd_config -nt /var/run/sshd.pid && echo reload
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
	exit 1
	;;
esac
rc_exit
