#! /bin/sh
# Copyright (c) 2000, 2001 SuSE GmbH Nuernberg, Germany.
#
# Author: Thorsten Kukuk <feedback@suse.de>
#
# init.d/ypxfrd
#
#   and symbolic its link
#
# /sbin/rcypxfrd
#
# System startup script for the nessus backend nessusd
#
### BEGIN INIT INFO
# Provides: ypxfrd
# Required-Start: portmap ypserv
# Required-Stop: portmap
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start rpc.ypxfrd to allow faster NIS map transfers
### END INIT INFO

YPXFRD_BIN=/usr/sbin/rpc.ypxfrd
test -x $YPXFRD_BIN || exit 5

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
. /etc/rc.status

# First reset status of this service
rc_reset

# Return values acc. to LSB for all commands but status:
# 0 - success
# 1 - misc error
# 2 - invalid or excess args
# 3 - unimplemented feature (e.g. reload)
# 4 - insufficient privilege
# 5 - program not installed
# 6 - program not configured
#
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signalling is not supported) are
# considered a success.

case "$1" in
    start)
	echo -n "Starting rpc.ypxfrd"
	## Start daemon with startproc(8). If this fails
	## the echo return value is set appropriate.

        ## Check if portmap is running, else abort with error
        checkproc /sbin/portmap
        if [ $? -ne 0 ]; then
          echo -n " . . . . . . . . . . No portmapper running";
          rc_failed
          rc_status -v
          rc_exit
        fi

	# startproc should return 0, even if service is
	# already running to match LSB spec.
	startproc $YPXFRD_BIN

	# Remember status and be verbose
	rc_status -v
	;;
    stop)
	echo -n "Shutting down rpc.ypxfrd"
	## Stop daemon with killproc(8) and if this fails
	## set echo the echo return value.

	killproc -TERM $YPXFRD_BIN

	# Remember status and be verbose
	rc_status -v
	;;
    try-restart)
	## Stop the service and if this succeeds (i.e. the
	## service was running before), start it again.
	$0 stop  &&  $0 start

	# Remember status and be quiet
	rc_status
	;;
    restart)
	## Stop the service and regardless of whether it was
	## running or not, start it again.
	$0 stop
	$0 start

	# Remember status and be quiet
	rc_status
	;;
    force-reload)
	## Signal the daemon to reload its config. Most daemons
	## do this on signal 1 (SIGHUP).
	## If it does not support it, restart.

	echo -n "Reload service rpc.ypxfrd"
	## if it supports it:
	killproc -HUP $YPXFRD_BIN
	rc_status -v
	;;
    reload)
	## Like force-reload, but if daemon does not support
	## signalling, do nothing (!)

	# If it supports signalling:
	echo -n "Reload service rpc.ypxfrd"
	killproc -HUP $YPXFRD_BIN
	rc_status -v
	;;
    status)
	echo -n "Checking for rpc.ypxfrd: "
	## Check status with checkproc(8), if process is running
	## checkproc will return with exit status 0.

	# Status has a slightly different for the status command:
	# 0 - service running
	# 1 - service dead, but /var/run/  pid  file exists
	# 2 - service dead, but /var/lock/ lock file exists
	# 3 - service not running

	# If checkproc would return LSB compliant ret values,
	# things could be a little bit easier here. This will
	# probably soon be the case ...
	checkproc $YPXFRD_BIN; rc=$?
	if test $rc = 0; then echo "OK"
	else echo "No process"
		if test -e /var/run/ypxfrd.pid;
		then exit 1
		else exit 3
		fi
	fi
	#rc_status
	;;
    probe)
	## Optional: Probe for the necessity of a reload,
	## give out the argument which is required for a reload.

	test /etc/ypserv.conf -nt /var/run/ypxfrd.pid && echo reload
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
	exit 1
	;;
esac
rc_exit
