." Manpage for qa_test_postmark.
." Contact Yi Xu <yxu@suse.com> to correct errors or typos.
.TH man 8 "05 Dec 2012" "1.0" "qa_test_postmark man page"
.SH NAME
qa_test_postmark
.SH SYNOPSIS
None.
.SH TYPE
test
.SH DESCRIPTION
A New File System Benchmark.
.br
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Existing file system benchmarks are deficient in portraying performance in the ephemeral small-file regime used by Internet software, especially for electronic mail, netnews, web-based commerce. PostMark is a new benchmark to measure performance for this class of application.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
External, no patches.
.SH LICENSE
Artistic License
.SH UPSTREAM
http://openbenchmarking.org/test/pts/postmark
.SH AUTHOR
NetApp
.SH MAINTAINER
Yi Xu <yxu@suse.com>
