#!/bin/bash
# flushb fixed!  Use CERBERUS_FLUSH_BUFFERS to enable.

#if [ ! -z "$CERBERUS_FLUSH_BUFFERS" ] ; then
	# this causes filesystem corruption with EXT2 unless you
	# have a good kernel.
	x='/usr/lib/ctcs2/bin/qa_test_newburn/flushb.real'
#	echo CERBERUS_FLUSH_BUFFERS set.  flushing $1
	if [ ! -x "$x" ] ; then {
		echo Warning.  flushb.real not present'!'
		exit 2
	} ; fi
	$x $1 >> /dev/null
#else
	exit
#fi
