#!/bin/bash
# ****************************************************************************
# Copyright (c) 2013 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#


export LANG=C

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf


TCF_FILE="$TCF_DIR/qa_virtualization-virt_install.tcf"
TCF_TRUE="/tmp/qa_virtualization-virt_install.tcf"

#detect the ENV and filter the install test cases

##Skip the windows cases

cat $TCF_FILE|sed '/ win-/{N;d}' >$TCF_TRUE

##filter for the products,all lists are from SPEC file
suse_version=`rpm --eval %{suse_version}`
if [ $suse_version -eq 1010 ];then
	#SLES 10 SP 4
	list="nw-65-sp7\|oes-2-fcs\|oes-2-sp1\|rhel-3\|rhel-4-u6\|rhel-4-u7\|rhel-5-fcs\|rhel-5-u1\|rhel-5-u2\|rhel-5-u3\|rhel-5-u4\|sle[ds]-10-sp1\|sle[ds]-10-sp2\|sled-10-sp3\|sle[ds]-10-fcs\|sled-11\|sles-11-fcs\|win-vista-fcs\|win-vista-sp1\|win-xp-sp1\|win-xp-sp2\|win-xp-fcs\|win-2k8-"
	sed -i "/$list/!d" $TCF_TRUE

elif [ $suse_version -eq 1110 ] ;then
	#SLES 11
	list="nw-65-sp8\|oes-2-sp3\|oes-11\|rhel-4-u8\|rhel-5-u1*[89]\|rhel-6-u[345]\|rhel-7\|sles-9-sp4\|sles-10-sp4\|sles-11-sp[123]\|sled-11-sp3\|win-vista-sp2\|win-xp-sp3|win-7-sp1\|win-8\|win-2k3-sp2\|win-2k8-sp2\|win-2k8r2\|win-2k12"
	#list="nw-65-sp8\|oes-11-sp2\|sles-11-sp3\|win-2k8r2-sp1\|win-2k3-sp2"
	sed -i "/$list/!d" $TCF_TRUE


elif [ $suse_version -eq 1315 ] ;then

	list="nw-65-sp8\|oes-11-sp[12]\|rhel-5-u1[0-9]\|rhel-6-u[5-9]]\|rhel-7\|sles-9-sp4\|sles-10-sp4\|sles-11-sp3\|sle[sd]-12\|win-vista-sp2\|win-xp-sp3|win-7-sp1\|win-8\|win-2k3-sp2\|win-2k8-sp2\|win-2k8r2-sp1\|win-2k12"
	#list="oes-11-sp2\|sles-11-sp3\|sles-12\|win-2k8r2-sp1\|win-2k12r2-fcs"
	sed -i "/$list/!d" $TCF_TRUE

else

	echo "Can NOT detect the suse_version,test all"
fi


#remove all para-virtualization test on KVM host
if ! uname -a|grep -iq xen ;then
	#The host is KVM
	sed -i '/-pv-/d' $TCF_TRUE

fi
/usr/share/qa/virtautolib/lib/opt_gen.pl


thread=$1


if echo $thread|grep -q "^[0-9][0-9]*$" ;then
	#set the number
	num=$thread
	timer=7200
else
	#By default, we set thread = 4
	num=4
	timer=7200

fi


sed -i "0~$num {s/\$/\nwait\ntimer $timer/;}" $TCF_TRUE
sed -i "1s/^/timer $timer\n/" $TCF_TRUE
sed -i "\$s/$/\nwait/" $TCF_TRUE


$CTCS2_DIR/tools/run $TCF_TRUE
returncode=0

for file in `find /var/log/qa/ctcs2/ -name test_results`; do
	[ -z "$(cat $file)" ] && ((returncode+=1))
done

((returncode+=`find /var/log/qa/ctcs2/ -name test_results -exec grep "^[0-9] 0" {} \; | wc -l`))
hn=`cat /etc/HOSTNAME`
ARCH=`arch`

/usr/share/qa/tools/remote_qa_db_report.pl -b -c "Virtualization test results on $hn-$ARCH"

exit $returncode

