#!/bin/bash
# ****************************************************************************
# Copyright (c) 2013 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#


export LANG=C

CTCS2_DIR=/usr/lib/ctcs2
TCF_DIR=/usr/share/qa/tcf
TCF_FILE="$TCF_DIR/qa_virtualization-virt_install_withopt.tcf"

/usr/share/qa/virtautolib/lib/opt_gen.pl

#set the number parallel run

filter=$1

if [ -z "$filter" ];then
	#Set default product to run the installation
	filter=sles-11-sp3-64-fv
fi

TMP_TCF="/tmp/qa_virtualization-virt_install_withopt.tcf"

#Set 3 days timeout
echo "timer 259200" >$TMP_TCF

grep "$filter" $TCF_FILE >>$TMP_TCF

echo "wait" >>$TMP_TCF


$CTCS2_DIR/tools/run $TMP_TCF
returncode=0

for file in `find /var/log/qa/ctcs2/ -name test_results`; do
	[ -z "$(cat $file)" ] && ((returncode+=1))
done

((returncode+=`find /var/log/qa/ctcs2/ -name test_results -exec grep "^[0-9] 0" {} \; | wc -l`))
hn=`cat /etc/HOSTNAME`
ARCH=`arch`

/usr/share/qa/tools/remote_qa_db_report.pl -b -c "Virtualization test results on $hn-$ARCH"

exit $returncode

