#!/bin/bash
# ****************************************************************************
# Copyright (c) 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#


export LANG=C

if [ $# -ne 1 ] ; then
	echo "Usage $0 <ip>" >&2
	exit 1
fi

# Local server - dhcp server for the local subnet
MY_MAC="`/sbin/ifconfig br123 | grep HWaddr | awk '{ print $NF; }' | tr '[:upper:]' '[:lower:]'`"
MY_IP="192.168.123.1"

if ! /sbin/ifconfig | grep -qi "$MY_MAC" ; then
	# I'm not running it on the server, but this must be run on the server
	ssh rd-qa@$MY_IP ip2mac "$1"
	exit $?
fi

ip="$1"

# This host - static configuration!
if [ "$ip" == "$MY_IP" ] ; then
	echo "$MY_MAC"
	exit 0
fi
	

# First, try the static reports in the dhcpd.conf
mac=`get_mac_ip_pairs_from_dhcp_conf.pl | grep -i " $ip\$" | sed "s/ $ip\$//i"`

if [ "$mac" != "" ] ; then
	echo $mac | tr '[:upper:]' '[:lower:]'
	exit 0
fi

# Now, look for dynamic assignment
cat /var/lib/dhcp/db/dhcpd.leases | tr '[:upper:]' '[:lower:]' | grep '^[[:space:]]*lease \|^[[:space:]]*hardware ethernet\|^[[:space:]]*binding state'  | tac | while read line
do
	# always tripples:
	#   hardware ethernet MAC;
	#   binding state active/free;
	#   lease IP { -- we never get this here! - it's always read in the cycle body!
	
	# read mac address
	mac=`echo "$line" | sed 's/^[[:space:]]*hardware ethernet[[:space:]]\+\([a-fA-F0-9:]\+\)[[:space:]]*;.*$/\1/' | tr '[:upper:]' '[:lower:]'`


	read line
	if echo "$line" | grep -q 'binding state active;' ; then 
		active=1
	else
		active=0
	fi

	# read IP address
	read line
	
	if [ "$active" == "1" ] ; then
		# only actice leases are valid
		if echo "$line" | grep -q "lease[[:space:]]\+$ip[[:space:]]*{" ; then
			# this is the one
			echo $mac
			exit 0
		fi
	fi
done


