#!/bin/bash

export LANG=C

if [ $# -ne 1 ] ; then
	echo "Usage $0 <ip>" >&2
	exit 1
fi

# Local server - dhcp server for the local subnet
MY_MAC="`/sbin/ifconfig br123 | grep HWaddr | awk '{ print $NF; }' | tr '[:upper:]' '[:lower:]'`"
MY_IP="192.168.123.1"

if ! /sbin/ifconfig | grep -qi "$MY_MAC" ; then
	# I'm not running it on the server, but this must be run on the server
	ssh rd-qa@$MY_IP ip2mac "$1"
	exit $?
fi

ip="$1"

# This host - static configuration!
if [ "$ip" == "$MY_IP" ] ; then
	echo "$MY_MAC"
	exit 0
fi
	

# First, try the static reports in the dhcpd.conf
mac=`get_mac_ip_pairs_from_dhcp_conf.pl | grep -i " $ip\$" | sed "s/ $ip\$//i"`

if [ "$mac" != "" ] ; then
	echo $mac | tr '[:upper:]' '[:lower:]'
	exit 0
fi

# Now, look for dynamic assignment
cat /var/lib/dhcp/db/dhcpd.leases | tr '[:upper:]' '[:lower:]' | grep '^[[:space:]]*lease \|^[[:space:]]*hardware ethernet\|^[[:space:]]*binding state'  | tac | while read line
do
	# always tripples:
	#   hardware ethernet MAC;
	#   binding state active/free;
	#   lease IP { -- we never get this here! - it's always read in the cycle body!
	
	# read mac address
	mac=`echo "$line" | sed 's/^[[:space:]]*hardware ethernet[[:space:]]\+\([a-fA-F0-9:]\+\)[[:space:]]*;.*$/\1/' | tr '[:upper:]' '[:lower:]'`


	read line
	if echo "$line" | grep -q 'binding state active;' ; then 
		active=1
	else
		active=0
	fi

	# read IP address
	read line
	
	if [ "$active" == "1" ] ; then
		# only actice leases are valid
		if echo "$line" | grep -q "lease[[:space:]]\+$ip[[:space:]]*{" ; then
			# this is the one
			echo $mac
			exit 0
		fi
	fi
done

